# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils


@pytest.mark.igammac_
@pytest.mark.parametrize("shape", utils.POINTWISE_SHAPES)
# igammac_cuda does not support Half/BFloat16
@pytest.mark.parametrize("dtype", [torch.float32])
def test_igammac_(shape, dtype):
    # igammac_ is the in-place version
    # Generate positive random values for a and x
    inp1 = torch.rand(shape, dtype=dtype, device=flag_gems.device) + 0.1
    inp2 = torch.rand(shape, dtype=dtype, device=flag_gems.device) + 0.1
    ref_inp1 = utils.to_reference(inp1.clone(), True)
    ref_inp2 = utils.to_reference(inp2, True)

    ref_out = ref_inp1.igammac_(ref_inp2)
    with flag_gems.use_gems():
        res_out = inp1.igammac_(inp2)

    utils.gems_assert_close(res_out, ref_out, dtype)
    # igammac_ is in-place: also verify the mutated input tensor matches reference
    utils.gems_assert_close(inp1, ref_inp1, dtype)
