# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

# Custom shapes for pairwise distance computation
if cfg.QUICK_MODE:
    EUCLIDEAN_DIST_SHAPES = [
        ((4, 8), (5, 8)),
        ((32, 64), (32, 64)),
    ]
else:
    EUCLIDEAN_DIST_SHAPES = [
        ((4, 8), (5, 8)),
        ((8, 16), (8, 16)),
        ((16, 32), (12, 32)),
        ((32, 64), (32, 64)),
        ((64, 128), (64, 128)),
        ((128, 256), (128, 256)),
    ]


@pytest.mark.euclidean_dist
@pytest.mark.parametrize("shape", EUCLIDEAN_DIST_SHAPES)
# cdist_cuda does not support Half/BFloat16
@pytest.mark.parametrize("dtype", [torch.float32])
def test_euclidean_dist(shape, dtype):
    (n1, d), (n2, d2) = shape
    assert d == d2, "Inner dimensions must match"

    inp1 = torch.randn(n1, d, dtype=dtype, device=flag_gems.device)
    inp2 = torch.randn(n2, d, dtype=dtype, device=flag_gems.device)
    ref_inp1 = utils.to_reference(inp1)
    ref_inp2 = utils.to_reference(inp2)

    ref_out = torch._euclidean_dist(ref_inp1, ref_inp2)
    with flag_gems.use_gems():
        res_out = torch._euclidean_dist(inp1, inp2)

    utils.gems_assert_close(res_out, ref_out, dtype)
