# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def chebyshev_polynomial_v_func(x, n):
    x_fp32 = x.to(tl.float32)
    n_fp32 = n.to(tl.float32)
    acos_x = tl_extra_shim.acos(x_fp32)
    numerator = tl.cos((n_fp32 + 0.5) * acos_x)
    denominator = tl.cos(acos_x * 0.5)
    result = numerator / denominator
    return result.to(x.dtype)


def special_chebyshev_polynomial_v(x, n):
    logger.debug("GEMS_SUNRISE SPECIAL_CHEBYSHEV_POLYNOMIAL_V")
    return chebyshev_polynomial_v_func(x, n)
