# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def irshift_kernel(a, b):
    return a >> b


def __irshift__(self, other):
    """In-place right shift: self >>= other."""
    logger.debug("GEMS IRSHIFT")

    # Handle scalar other
    if not torch.is_tensor(other):
        other = torch.tensor(other, dtype=self.dtype, device=self.device)

    # In-place: store result back in self
    return irshift_kernel(self, other, out0=self)
