# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import flag_gems  # noqa: F401
from flag_gems.ops.bitwise_left_shift import bitwise_left_shift

logger = logging.getLogger(__name__)


def __lshift__(self, other):
    logger.debug("GEMS LSHIFT")
    return bitwise_left_shift(self, other)
