# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def add_relu_func(x, y):
    # Compute relu(x + y) = max(0, x + y)
    result = x + y
    return tl.where(result > 0, result, 0)


def _add_relu(A, B):
    logger.debug("GEMS ADD_RELU")
    if isinstance(A, torch.Tensor) and isinstance(B, torch.Tensor):
        if B.device != A.device:
            B = B.to(A.device)
        return add_relu_func(A, B)
    elif isinstance(A, torch.Tensor):
        return add_relu_func(A, B)
    elif isinstance(B, torch.Tensor):
        return add_relu_func(A, B)
    else:
        return torch.tensor(max(0, A + B))
