# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def convert_weight_to_int4pack_kernel(
    inp_ptr,
    out_ptr,
    M,
    N,
    innerKTiles: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Convert weight tensor to int4 packed format.

    Input: int32 tensor of shape (M, N)
    Output: uint8 tensor of shape (M, N//2) where each byte contains two 4-bit values

    The packing follows the pattern: for each pair of int4 values (a, b),
    they are packed as: (b << 4) | a  (little-endian within the byte)
    """
    # Each program processes one row
    row_idx = tle.program_id(0)
    if row_idx >= M:
        return

    # Each thread processes BLOCK_SIZE output elements
    col_offs = tl.arange(0, BLOCK_SIZE)
    out_n = col_offs
    out_mask = out_n < (N // 2)

    # Input offsets for even and odd positions
    even_inp_offs = out_n * 2
    odd_inp_offs = out_n * 2 + 1
    inp_even_mask = even_inp_offs < N
    inp_odd_mask = odd_inp_offs < N

    # Load values
    even_ptrs = inp_ptr + row_idx * N + even_inp_offs
    odd_ptrs = inp_ptr + row_idx * N + odd_inp_offs

    even_val = tl.load(even_ptrs, mask=inp_even_mask, other=0)
    odd_val = tl.load(odd_ptrs, mask=inp_odd_mask, other=0)

    # Mask to 4 bits (int4 range: 0-15)
    even_val = even_val & 0xF
    odd_val = odd_val & 0xF

    # Pack: lower 4 bits = even, upper 4 bits = odd
    packed = (odd_val << 4) | even_val

    # Store output
    out_ptrs = out_ptr + row_idx * (N // 2) + out_n
    tl.store(out_ptrs, packed, mask=out_mask)


def _convert_weight_to_int4pack(inp: torch.Tensor, innerKTiles: int) -> torch.Tensor:
    logger.debug("GEMS CONVERT_WEIGHT_TO_INT4PACK")

    # innerKTiles validation: PyTorch requires innerKTiles in {2, 4, 8}.
    # NOTE: The current kernel implements simple byte-pair packing (adjacent
    # int4 values packed into one uint8 byte), producing output shape (M, N//2).
    # PyTorch's native CUDA kernel produces a Marlin-style tiled int32 output
    # whose shape depends on innerKTiles: (M/8, N/(8*innerKTiles), 32, innerKTiles/2).
    # For full compatibility with PyTorch's int4 quantization ecosystem,
    # the Marlin tiled format should be implemented in a future update.
    assert innerKTiles in (
        2,
        4,
        8,
    ), f"innerKTiles must be 2, 4, or 8, got {innerKTiles}"

    M, N = inp.shape
    # Ensure N is divisible by 2
    assert N % 2 == 0, f"N must be divisible by 2, got {N}"

    # Output shape is N//2 (each byte stores 2 int4 values)
    out = torch.empty((M, N // 2), dtype=torch.uint8, device=inp.device)

    # Define block size - each thread processes BLOCK_SIZE output elements
    BLOCK_SIZE = 64

    grid = lambda META: (M,)

    with torch_device_fn.device(inp.device):
        convert_weight_to_int4pack_kernel[grid](
            inp,
            out,
            M,
            N,
            innerKTiles,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    return out
