# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry, libtuner

logger = logging.getLogger(__name__)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("_conj"),
    key=["n_elements"],
)
@triton.jit
def _conj_kernel(in_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Complex numbers are stored as interleaved real/imaginary (real, imag, real, imag, ...)
    # Each complex element takes 2 float32 slots
    base = offsets * 2

    # Load real and imaginary parts
    real = tl.load(in_ptr + base, mask=mask)
    imag = tl.load(in_ptr + base + 1, mask=mask)

    # Store: real unchanged, imaginary negated (conjugate)
    tl.store(out_ptr + base, real, mask=mask)
    tl.store(out_ptr + base + 1, -imag, mask=mask)


def _conj(input: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS CONJ")
    if not input.is_complex():
        raise RuntimeError("_conj only supports complex tensors")

    # If input already has conjugate bit set, conj(conj(x)) = x.
    # Return a physical copy of the original (unconjugated) storage data.
    if input.is_conj():
        # input logical value = conj(storage). We need conj(logical) = storage.
        # Step 1: resolve_conj physically materializes the logical value → [a-bi]
        resolved = input.resolve_conj()  # no conj bit, data = conj(storage)
        # Step 2: conj_physical negates imaginary → storage data [a+bi]
        return torch.conj_physical(resolved)

    n_elements = input.numel()
    # Ensure contiguous memory layout for efficient loading
    src = input if input.is_contiguous() else input.contiguous()
    output = torch.empty_like(src)

    # Convert complex tensor to float32 tensor view (real, imag interleaved)
    in_real_ptr = torch.view_as_real(src)
    out_real_ptr = torch.view_as_real(output)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    _conj_kernel[grid](in_real_ptr, out_real_ptr, n_elements)

    return output
