# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _embedding_bag_per_sample_weights_backward_kernel(
    grad_ptr,
    weight_ptr,
    indices_ptr,
    offset2bag_ptr,
    output_ptr,
    num_samples,
    embedding_dim,
    stride_grad,
    stride_weight,
    NUM_BLOCKS: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    """Kernel for computing gradient w.r.t. per_sample_weights.

    For each sample i:
        output[i] = dot(grad[offset2bag[i]], weight[indices[i]])

    Uses a loop over NUM_BLOCKS blocks of size BLOCK_D to support
    arbitrarily large embedding dimensions.

    Args:
        grad_ptr: pointer to grad output tensor (num_bags, embedding_dim)
        weight_ptr: pointer to weight tensor (num_embeddings, embedding_dim)
        indices_ptr: pointer to indices tensor (num_samples,)
        offset2bag_ptr: pointer to offset2bag tensor (num_samples,)
        output_ptr: pointer to output tensor (num_samples,)
        num_samples: number of samples (length of indices/offset2bag)
        embedding_dim: embedding dimension
        stride_grad: stride for grad tensor in embedding_dim dimension
        stride_weight: stride for weight tensor in embedding_dim dimension
        NUM_BLOCKS: number of BLOCK_D-sized blocks to iterate over
        BLOCK_D: block size for embedding dimension (constexpr, <= 1024)
    """
    pid = tl.program_id(0)

    # Load indices and offset2bag for this sample
    idx = tl.load(indices_ptr + pid).to(tl.int32)
    bag_idx = tl.load(offset2bag_ptr + pid).to(tl.int32)

    # Accumulate partial dot products over blocks of BLOCK_D
    result = 0.0
    for block_idx in range(NUM_BLOCKS):
        offs_d = block_idx * BLOCK_D + tl.arange(0, BLOCK_D)
        mask_d = offs_d < embedding_dim

        # Load weight[indices[i], offs_d]
        weight_offs = idx * stride_weight + offs_d
        w = tl.load(weight_ptr + weight_offs, mask=mask_d, other=0.0).to(tl.float32)

        # Load grad[offset2bag[i], offs_d]
        grad_offs = bag_idx * stride_grad + offs_d
        g = tl.load(grad_ptr + grad_offs, mask=mask_d, other=0.0).to(tl.float32)

        # Accumulate partial dot product
        result += tl.sum(g * w)

    # Store result
    tl.store(output_ptr + pid, result)


def _embedding_bag_per_sample_weights_backward(
    grad: torch.Tensor,
    weight: torch.Tensor,
    indices: torch.Tensor,
    offsets: torch.Tensor,
    offset2bag: torch.Tensor,
    mode: int,
    padding_idx: int = -1,
) -> torch.Tensor:
    """Compute gradient of embedding bag w.r.t. per_sample_weights.

    Args:
        grad: gradient tensor of shape (num_bags, embedding_dim)
        weight: embedding table of shape (num_embeddings, embedding_dim)
        indices: indices into embedding table of shape (num_samples,)
        offsets: bag boundaries of shape (num_bags + 1,)
        offset2bag: mapping from each sample to its bag of shape (num_samples,)
        mode: embedding bag mode (0=sum, 1=mean). Kept for API compatibility;
            per_sample_weights backward is the same regardless of mode since
            per_sample_weights only applies in mode=sum.
        padding_idx: padding index. Gradients at positions where
            indices == padding_idx are zeroed out.

    Returns:
        Gradient w.r.t. per_sample_weights of shape (num_samples,)
    """
    logger.debug("GEMS: _embedding_bag_per_sample_weights_backward")

    assert indices.dtype in (
        torch.int32,
        torch.int64,
    ), "Indices must be int32 or int64."
    assert (
        grad.device == weight.device == indices.device == offset2bag.device
    ), "All inputs must be on the same device."

    num_samples = indices.numel()
    embedding_dim = weight.shape[1]

    assert num_samples > 0, "num_samples must be positive"
    assert embedding_dim > 0, "embedding_dim must be positive"

    # Prepare output tensor (use grad.dtype for output consistency)
    output = torch.empty(num_samples, device=grad.device, dtype=torch.float32)

    # Make inputs contiguous
    grad = grad.contiguous()
    weight = weight.contiguous()
    indices = indices.contiguous()
    offset2bag = offset2bag.contiguous()

    BLOCK_D = triton.next_power_of_2(min(embedding_dim, 1024))
    NUM_BLOCKS = triton.cdiv(embedding_dim, BLOCK_D)
    grid = (num_samples,)

    _embedding_bag_per_sample_weights_backward_kernel[grid](
        grad,
        weight,
        indices,
        offset2bag,
        output,
        num_samples,
        embedding_dim,
        grad.stride(0),
        weight.stride(0),
        NUM_BLOCKS=NUM_BLOCKS,
        BLOCK_D=BLOCK_D,
    )

    # Zero out gradients for padding_idx positions
    if padding_idx >= 0:
        output[indices == padding_idx] = 0.0

    return output.to(grad.dtype)
