# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

import flag_gems

logger = logging.getLogger(__name__)


def _make_dep_token(
    *,
    dtype=None,
    layout=None,
    device=None,
    pin_memory=None,
    memory_format=None,
):
    """
    Create a dependency token for TorchScript tracing.

    This operator creates a 0-dimensional (scalar) tensor that can be used
    for dependency tracking in TorchScript. The value of the returned tensor
    is uninitialized and should not be used.
    """
    logger.debug("GEMS _MAKE_DEP_TOKEN")
    if dtype is None:
        dtype = torch.float32
    if device is None:
        device = flag_gems.device

    # The returned tensor is uninitialized by definition; no kernel is needed.
    out = torch.empty((), dtype=dtype, device=device)

    return out
