# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _nested_view_from_buffer_copy(
    self: torch.Tensor,
    nested_size: torch.Tensor,
    nested_strides: torch.Tensor,
    offsets: torch.Tensor,
):
    """Low-level operation that creates a nested tensor from a flat buffer
    given sizes, strides and offsets of each component."""

    from flag_gems.runtime.backend._metax.ops._nested_view_from_buffer_copy import (
        _nested_view_from_buffer_copy as _metax_nested_view_from_buffer_copy,
    )

    logger.debug("GEMS _NESTED_VIEW_FROM_BUFFER_COPY")
    return _metax_nested_view_from_buffer_copy(
        self, nested_size, nested_strides, offsets
    )


__all__ = ["_nested_view_from_buffer_copy"]
