# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _pdist_forward_p2_kernel(
    x_ptr,
    out_ptr,
    N: tl.constexpr,
    M,
    stride_x,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=2 case (Euclidean distance)."""
    pid = tle.program_id(0)

    # Each program computes one output element (one pair of rows)
    # For output index pid, find the corresponding (i, j) pair where i < j
    #
    # pdist output ordering for N=4:
    # - Row 0 pairs: indices 0,1,2 -> pairs (0,1), (0,2), (0,3)
    # - Row 1 pairs: indices 3,4 -> pairs (1,2), (1,3)
    # - Row 2 pairs: index 5 -> pair (2,3)
    #
    # cum_before_i = i*N - i*(i+1)//2 = pairs before row i
    # For N=4: cum_before_0=0, cum_before_1=3, cum_before_2=5, cum_before_3=6
    #
    # Find i such that: cum_before_i <= pid < cum_before_{i+1}
    # Then row_i = i, and col_offset = pid - cum_before_i, row_j = i + 1 + col_offset

    # Linear search for row
    # We want to find the largest i where cum_before_i <= pid
    row_i = tl.full([], 0, dtype=tl.int64)
    for i in range(0, N):
        cum_before_i = i * N - i * (i + 1) // 2
        # Update row_i when pid >= cum_before_i (we're at or past this row)
        row_i = tl.where(pid >= cum_before_i, i, row_i)

    cum_before_row_i = row_i * N - row_i * (row_i + 1) // 2
    col_offset = pid - cum_before_row_i
    row_j = row_i + 1 + col_offset

    # Compute squared distance between row_i and row_j
    i_offset = row_i * stride_x
    j_offset = row_j * stride_x

    sum_sq = 0.0
    for m in range(0, M, BLOCK_M):
        m_offsets = m + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        xi = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        xj = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = xi - xj
        sum_sq += tl.sum(diff * diff)

    dist = tl.sqrt(sum_sq)
    tl.store(out_ptr + pid, dist)


@libentry()
@triton.jit
def _pdist_forward_p1_kernel(
    x_ptr,
    out_ptr,
    N: tl.constexpr,
    M,
    stride_x,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=1 case (Manhattan distance)."""
    pid = tle.program_id(0)

    row_i = tl.full([], 0, dtype=tl.int64)
    for i in range(0, N):
        cum_before_i = i * N - i * (i + 1) // 2
        row_i = tl.where(pid >= cum_before_i, i, row_i)

    cum_before_row_i = row_i * N - row_i * (row_i + 1) // 2
    col_offset = pid - cum_before_row_i
    row_j = row_i + 1 + col_offset

    i_offset = row_i * stride_x
    j_offset = row_j * stride_x

    sum_abs = 0.0
    for m in range(0, M, BLOCK_M):
        m_offsets = m + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        xi = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        xj = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = xi - xj
        sum_abs += tl.sum(tl.abs(diff))

    tl.store(out_ptr + pid, sum_abs)


@libentry()
@triton.jit
def _pdist_forward_inf_kernel(
    x_ptr,
    out_ptr,
    N: tl.constexpr,
    M,
    stride_x,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for p=inf case (Chebyshev distance)."""
    pid = tle.program_id(0)

    row_i = tl.full([], 0, dtype=tl.int64)
    for i in range(0, N):
        cum_before_i = i * N - i * (i + 1) // 2
        row_i = tl.where(pid >= cum_before_i, i, row_i)

    cum_before_row_i = row_i * N - row_i * (row_i + 1) // 2
    col_offset = pid - cum_before_row_i
    row_j = row_i + 1 + col_offset

    i_offset = row_i * stride_x
    j_offset = row_j * stride_x

    max_abs = 0.0
    for m in range(0, M, BLOCK_M):
        m_offsets = m + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        xi = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        xj = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = tl.abs(xi - xj)
        max_abs = tl.maximum(max_abs, tl.max(diff))

    tl.store(out_ptr + pid, max_abs)


@libentry()
@triton.jit
def _pdist_forward_general_kernel(
    x_ptr,
    out_ptr,
    N: tl.constexpr,
    M,
    p_val,
    stride_x,
    BLOCK_M: tl.constexpr,
):
    """Forward kernel for general p value."""
    pid = tle.program_id(0)

    row_i = tl.full([], 0, dtype=tl.int64)
    for i in range(0, N):
        cum_before_i = i * N - i * (i + 1) // 2
        row_i = tl.where(pid >= cum_before_i, i, row_i)

    cum_before_row_i = row_i * N - row_i * (row_i + 1) // 2
    col_offset = pid - cum_before_row_i
    row_j = row_i + 1 + col_offset

    i_offset = row_i * stride_x
    j_offset = row_j * stride_x

    sum_pow = 0.0
    for m in range(0, M, BLOCK_M):
        m_offsets = m + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        xi = tl.load(x_ptr + i_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )
        xj = tl.load(x_ptr + j_offset + m_offsets, mask=m_mask, other=0.0).to(
            tl.float32
        )

        diff = tl.abs(xi - xj)
        powered = tl.where(diff > 0.0, tl.exp(p_val * tl.log(diff)), 0.0)
        sum_pow += tl.sum(powered)

    dist = tl.where(sum_pow > 0.0, tl.exp(tl.log(sum_pow) / p_val), 0.0)

    tl.store(out_ptr + pid, dist)


def _pdist_forward(x, p=2.0):
    """Compute pairwise distances between rows of x.

    Args:
        x: Input tensor of shape (N, M)
        p: The norm degree. Default is 2.0 (Euclidean distance).

    Returns:
        Output tensor of shape (N*(N-1)//2,) containing pairwise distances.
    """
    logger.debug("GEMS _PDIST_FORWARD")

    assert x.dtype in (
        torch.float32,
        torch.float64,
    ), f"pdist only supports float32 and float64, got {x.dtype}"
    assert x.ndim == 2, "pdist only supports 2D input"
    N = x.shape[0]
    M = x.shape[1]

    if N < 2:
        return torch.empty((0,), dtype=x.dtype, device=x.device)

    x = x.contiguous()
    n_pairs = N * (N - 1) // 2
    out = torch.empty((n_pairs,), dtype=x.dtype, device=x.device)

    BLOCK_M = min(triton.next_power_of_2(M), 1024)
    grid = (n_pairs,)

    with torch_device_fn.device(x.device):
        if p == 2.0:
            _pdist_forward_p2_kernel[grid](
                x,
                out,
                N,
                M,
                x.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif p == 1.0:
            _pdist_forward_p1_kernel[grid](
                x,
                out,
                N,
                M,
                x.stride(0),
                BLOCK_M=BLOCK_M,
            )
        elif abs(p) == float("inf"):
            _pdist_forward_inf_kernel[grid](
                x,
                out,
                N,
                M,
                x.stride(0),
                BLOCK_M=BLOCK_M,
            )
        else:
            _pdist_forward_general_kernel[grid](
                x,
                out,
                N,
                M,
                p,
                x.stride(0),
                BLOCK_M=BLOCK_M,
            )

    return out
