# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _upsample_nearest_exact3d_kernel(
    in_ptr,
    out_ptr,
    N,
    C,
    ID,
    IH,
    IW,
    OD,
    OH,
    OW,
    sN_in,
    sC_in,
    sD_in,
    sH_in,
    sW_in,
    sN_out,
    sC_out,
    sD_out,
    sH_out,
    sW_out,
    use_scales: tl.constexpr,
    scale_d,
    scale_h,
    scale_w,
    BLOCK_DHW: tl.constexpr,
):
    pid_dhw = tl.program_id(0)
    pid_nc = tl.program_id(1)

    offs_dhw = pid_dhw * BLOCK_DHW + tl.arange(0, BLOCK_DHW)
    mask = offs_dhw < OD * OH * OW

    # Compute (n, c) from flattened plane index
    nc = pid_nc
    n = nc // C
    c = nc - n * C

    base_in = n * sN_in + c * sC_in
    base_out = n * sN_out + c * sC_out

    # Compute output depth, height, width indices
    ow = offs_dhw % OW
    oh = (offs_dhw // OW) % OH
    od = offs_dhw // (OW * OH)

    # Compute source indices using the "nearest exact" formula from PyTorch:
    # src_index = min(floor((dst_index + 0.5) * (IN / OUT)), IN - 1)
    # When scale is given: scale = OUT / IN, so IN / OUT = 1 / scale
    od_f = od.to(tl.float32)
    oh_f = oh.to(tl.float32)
    ow_f = ow.to(tl.float32)

    if use_scales:
        # scale here is OUT/IN, so reciprocal gives IN/OUT
        id_f = tl.floor((od_f + 0.5) / scale_d)
        ih_f = tl.floor((oh_f + 0.5) / scale_h)
        iw_f = tl.floor((ow_f + 0.5) / scale_w)
    else:
        # IN/OUT ratio directly
        id_f = tl.floor((od_f + 0.5) * ID / OD)
        ih_f = tl.floor((oh_f + 0.5) * IH / OH)
        iw_f = tl.floor((ow_f + 0.5) * IW / OW)

    id = id_f.to(tl.int32)
    ih = ih_f.to(tl.int32)
    iw = iw_f.to(tl.int32)

    id = tl.minimum(id, ID - 1)
    ih = tl.minimum(ih, IH - 1)
    iw = tl.minimum(iw, IW - 1)

    # Compute input offset: base_in + id * sD_in + ih * sH_in + iw * sW_in
    in_ptrs = in_ptr + base_in + id * sD_in + ih * sH_in + iw * sW_in
    x = tl.load(in_ptrs, mask=mask)

    # Compute output offset: base_out + od * sD_out + oh * sH_out + ow * sW_out
    out_ptrs = out_ptr + base_out + od * sD_out + oh * sH_out + ow * sW_out
    tl.store(out_ptrs, x, mask=mask)


def _parse_size_3d(val):
    if val is None:
        return (None, None, None)
    if isinstance(val, torch.Size):
        return tuple(int(v) for v in val) if len(val) > 0 else (None, None, None)
    if isinstance(val, (list, tuple)):
        if len(val) == 0:
            return (None, None, None)
        return tuple(int(v) for v in val)
    return (int(val), int(val), int(val))


def _parse_scale_3d(val):
    if val is None:
        return (None, None, None)
    if isinstance(val, (list, tuple)):
        if len(val) == 0:
            return (None, None, None)
        return tuple(float(v) for v in val)
    return (float(val), float(val), float(val))


def _compute_out_size(id, ih, iw, output_size, scale):
    if output_size is not None:
        return output_size
    if scale is None:
        raise ValueError(
            "Either output_size or scale must be provided for _upsample_nearest_exact3d."
        )
    # Follow common convention: OD = floor(ID * scale_d), etc.
    od = int(math.floor(id * scale[0])) if scale[0] is not None else None
    oh = int(math.floor(ih * scale[1])) if scale[1] is not None else None
    ow = int(math.floor(iw * scale[2])) if scale[2] is not None else None
    return (od, oh, ow)


def _launch_upsample_nearest_exact3d_kernel(input, out, output_size=None, scale=None):
    if input.ndim != 5:
        raise ValueError(
            f"_upsample_nearest_exact3d expects a 5D tensor (N, C, D, H, W); got shape {tuple(input.shape)}"
        )
    if not input.is_cuda or not out.is_cuda:
        # Fallback to the native operator on CPU or non-CUDA devices
        return torch.ops.aten._upsample_nearest_exact3d(
            input, list(out.shape[-3:]), scale if scale else None
        )

    N, C, ID, IH, IW = input.shape
    OD, OH, OW = out.shape[-3:]

    sN_in, sC_in, sD_in, sH_in, sW_in = input.stride()
    sN_out, sC_out, sD_out, sH_out, sW_out = out.stride()

    BLOCK_DHW = 256
    grid = (triton.cdiv(OD * OH * OW, BLOCK_DHW), N * C)

    use_scales = scale is not None and output_size is None
    scale_d = float(scale[0]) if use_scales else 1.0
    scale_h = float(scale[1]) if use_scales else 1.0
    scale_w = float(scale[2]) if use_scales else 1.0

    _upsample_nearest_exact3d_kernel[grid](
        input,
        out,
        N,
        C,
        ID,
        IH,
        IW,
        OD,
        OH,
        OW,
        sN_in,
        sC_in,
        sD_in,
        sH_in,
        sW_in,
        sN_out,
        sC_out,
        sD_out,
        sH_out,
        sW_out,
        use_scales=use_scales,
        scale_d=scale_d,
        scale_h=scale_h,
        scale_w=scale_w,
        BLOCK_DHW=BLOCK_DHW,
    )
    return out


def _extract_io_and_params(args, kwargs, expect_out=False):
    # Extract input tensor
    in_t = kwargs.get("input", None)
    if in_t is None:
        in_t = kwargs.get("self", None)
    if in_t is None and len(args) > 0 and isinstance(args[0], torch.Tensor):
        in_t = args[0]
        args = args[1:]
    if in_t is None or not isinstance(in_t, torch.Tensor):
        raise ValueError("Input tensor not found for _upsample_nearest_exact3d.")

    # Extract output_size / scales from kwargs or remaining args
    output_size = kwargs.get(
        "output_size", kwargs.get("size", kwargs.get("output_size_list", None))
    )
    scales = kwargs.get(
        "scale_factor",
        kwargs.get("scales", kwargs.get("scale_factors", kwargs.get("scale", None))),
    )

    # If positional arguments contain size and/or scales
    # Try to interpret next positional as output_size if present and not a tensor
    pos = 0
    if (
        output_size is None
        and pos < len(args)
        and not isinstance(args[pos], torch.Tensor)
    ):
        output_size = args[pos]
        pos += 1
    if scales is None and pos < len(args) and not isinstance(args[pos], torch.Tensor):
        scales = args[pos]
        pos += 1

    out_t = None
    if expect_out:
        out_t = kwargs.get("out", None)
        if out_t is None:
            # find last tensor among remaining args as out
            for a in reversed(args):
                if isinstance(a, torch.Tensor):
                    out_t = a
                    break
        if out_t is None:
            raise ValueError(
                "Output tensor 'out' not found for _upsample_nearest_exact3d_out."
            )

    # Normalize 3D size and scale
    out_dhw = _parse_size_3d(output_size)
    scale_dhw = _parse_scale_3d(scales)

    return in_t, out_t, out_dhw, scale_dhw


def _prepare_out_tensor(in_t, out_dhw, scale_dhw, dtype=None, device=None):
    N, C, ID, IH, IW = in_t.shape
    OD, OH, OW = _compute_out_size(ID, IH, IW, out_dhw, scale_dhw)
    if OD < 0 or OH < 0 or OW < 0:
        raise ValueError("Output dimensions must be non-negative.")
    if dtype is None:
        dtype = in_t.dtype
    if device is None:
        device = in_t.device
    return torch.empty((N, C, OD, OH, OW), dtype=dtype, device=device)


def _upsample_nearest_exact3d(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT3D")
    in_t, _, out_dhw, scale_dhw = _extract_io_and_params(args, kwargs, expect_out=False)
    out_t = _prepare_out_tensor(in_t, out_dhw, scale_dhw)
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact3d_kernel(
        in_t, out_t, output_size=out_dhw, scale=scale_dhw
    )


def _upsample_nearest_exact3d_out(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT3D_OUT")
    in_t, out_t, out_dhw, scale_dhw = _extract_io_and_params(
        args, kwargs, expect_out=True
    )
    if out_t.ndim != 5:
        raise ValueError(
            f"Out tensor must be 5D (N, C, D, H, W); got shape {tuple(out_t.shape)}"
        )
    # Validate that out_t has the correct computed dimensions if parameters are provided
    expected_dhw = _compute_out_size(
        in_t.shape[-3], in_t.shape[-2], in_t.shape[-1], out_dhw, scale_dhw
    )
    if out_t.shape[-3:] != expected_dhw:
        raise ValueError(
            f"Provided out tensor has shape {tuple(out_t.shape)} "
            f"but expected {(in_t.shape[0], in_t.shape[1]) + expected_dhw}."
        )
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact3d_kernel(
        in_t, out_t, output_size=out_dhw, scale=scale_dhw
    )


def _upsample_nearest_exact3d_vec(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT3D_VEC")
    # Treat vec the same as base variant, allowing list-like output_size/scales
    in_t, _, out_dhw, scale_dhw = _extract_io_and_params(args, kwargs, expect_out=False)
    out_t = _prepare_out_tensor(in_t, out_dhw, scale_dhw)
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact3d_kernel(
        in_t, out_t, output_size=out_dhw, scale=scale_dhw
    )
