# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _upsample_nearest_exact2d_kernel(
    in_ptr,
    out_ptr,
    N,
    C,
    IH,
    IW,
    OH,
    OW,
    sN_in,
    sC_in,
    sH_in,
    sW_in,
    sN_out,
    sC_out,
    sH_out,
    sW_out,
    use_scales: tl.constexpr,
    scale_h,
    scale_w,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    nc_stride = tl.num_programs(axis=1)
    NC = N * C
    nc_iter = tl.program_id(axis=1)

    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    ow = idx % OW
    oh = idx // OW % OH

    # Compute source indices ih, iw for each output index oh, ow
    if use_scales:
        ih = tl.floor(oh.to(tl.float32) / scale_h).to(tl.int32)
        iw = tl.floor(ow.to(tl.float32) / scale_w).to(tl.int32)
    else:
        ih = (oh * IH) // OH
        iw = (ow * IW) // OW
    ih = tl.minimum(ih, IH - 1)
    iw = tl.minimum(iw, IW - 1)

    # Compute n and c from flattened nc index
    nc = nc_iter
    n = nc // C
    c = nc - n * C

    # Compute base offsets for this plane
    base_offset_in = n * sN_in + c * sC_in
    base_offset_out = n * sN_out + c * sC_out

    while nc_iter < NC:
        offset_in = base_offset_in + ih * sH_in + iw * sW_in
        offset_out = base_offset_out + oh * sH_out + ow * sW_out
        data = tl.load(in_ptr + offset_in)
        tl.store(out_ptr + offset_out, data)
        # Advance to next plane: IH*IW elements in input, OH*OW in output
        base_offset_in += nc_stride * IH * IW
        base_offset_out += nc_stride * OH * OW
        nc_iter += nc_stride


def _parse_size_2d(val):
    if val is None:
        return None, None
    if isinstance(val, torch.Size):
        return (
            int(val[-2]) if len(val) > 1 else None,
            int(val[-1]) if len(val) > 0 else None,
        )
    if isinstance(val, (list, tuple)):
        if len(val) == 0:
            return None, None
        if len(val) == 1:
            return val[0], val[0]
        return int(val[0]), int(val[1])
    return int(val), int(val)


def _parse_scale_2d(val):
    if val is None:
        return None, None
    if isinstance(val, (list, tuple)):
        if len(val) == 0:
            return None, None
        if len(val) == 1:
            return float(val[0]), float(val[0])
        return float(val[0]), float(val[1])
    return float(val), float(val)


def _compute_out_size(ih, iw, output_size, scale):
    if output_size is not None:
        oh, ow = output_size
        return int(oh), int(ow)
    if scale is None:
        raise ValueError(
            "Either output_size or scale must be provided for _upsample_nearest_exact2d."
        )
    scale_h, scale_w = scale
    # Follow common convention: OH = floor(IH * scale_h), OW = floor(IW * scale_w)
    return int(math.floor(ih * scale_h)), int(math.floor(iw * scale_w))


def _launch_upsample_nearest_exact2d_kernel(input, out, output_size=None, scale=None):
    if input.ndim != 4:
        raise ValueError(
            f"_upsample_nearest_exact2d expects a 4D tensor (N, C, H, W); got shape {tuple(input.shape)}"
        )
    if not input.is_cuda or not out.is_cuda:
        # Fallback to the native operator on CPU or non-CUDA devices
        oh, ow = out.shape[-2:]
        return torch.ops.aten._upsample_nearest_exact2d(
            input,
            [oh, ow],
            [scale[0]] if scale is not None else None,
            [scale[1]] if scale is not None else None,
        )

    N, C, IH, IW = input.shape
    OH, OW = out.shape[-2:]

    # Fixed tile size covers one output pixel row segment per program.
    BLOCK_SIZE = 256
    total_threads = OH * OW
    grid = (
        triton.cdiv(total_threads, BLOCK_SIZE),
        triton.cdiv(N * C, 4),
    )

    use_scales = scale is not None and output_size is None
    scale_h = float(scale[0]) if use_scales else 1.0
    scale_w = float(scale[1]) if use_scales else 1.0

    _upsample_nearest_exact2d_kernel[grid](
        input,
        out,
        N,
        C,
        IH,
        IW,
        OH,
        OW,
        input.stride(0),
        input.stride(1),
        input.stride(2),
        input.stride(3),
        out.stride(0),
        out.stride(1),
        out.stride(2),
        out.stride(3),
        use_scales=use_scales,
        scale_h=scale_h,
        scale_w=scale_w,
        BLOCK_SIZE=BLOCK_SIZE,
    )
    return out


def _extract_io_and_params(args, kwargs, expect_out=False):
    # Extract input tensor
    in_t = kwargs.get("input", None)
    if in_t is None:
        in_t = kwargs.get("self", None)
    if in_t is None and len(args) > 0 and isinstance(args[0], torch.Tensor):
        in_t = args[0]
        args = args[1:]
    if in_t is None or not isinstance(in_t, torch.Tensor):
        raise ValueError("Input tensor not found for _upsample_nearest_exact2d.")

    # Extract output_size / scales from kwargs or remaining args
    output_size = kwargs.get(
        "output_size", kwargs.get("size", kwargs.get("output_size_list", None))
    )
    scales = kwargs.get(
        "scale_factor",
        kwargs.get("scales", kwargs.get("scale_factors", kwargs.get("scale", None))),
    )

    # If positional arguments contain size and/or scales
    # Try to interpret next positional as output_size if present and not a tensor
    pos = 0
    if (
        output_size is None
        and pos < len(args)
        and not isinstance(args[pos], torch.Tensor)
    ):
        output_size = args[pos]
        pos += 1
    if scales is None and pos < len(args) and not isinstance(args[pos], torch.Tensor):
        scales = args[pos]
        pos += 1

    out_t = None
    if expect_out:
        out_t = kwargs.get("out", None)
        if out_t is None:
            # find last tensor among remaining args as out
            for a in reversed(args):
                if isinstance(a, torch.Tensor):
                    out_t = a
                    break
        if out_t is None:
            raise ValueError(
                "Output tensor 'out' not found for _upsample_nearest_exact2d_out."
            )

    # Normalize size and scale
    out_h, out_w = _parse_size_2d(output_size)
    scale_h, scale_w = _parse_scale_2d(scales)

    return in_t, out_t, (out_h, out_w), (scale_h, scale_w)


def _prepare_out_tensor(in_t, out_size, scale, dtype=None, device=None):
    N, C, IH, IW = in_t.shape
    OH, OW = _compute_out_size(IH, IW, out_size, scale)
    if OH < 0 or OW < 0:
        raise ValueError("Output size must be non-negative.")
    if dtype is None:
        dtype = in_t.dtype
    if device is None:
        device = in_t.device
    return torch.empty((N, C, OH, OW), dtype=dtype, device=device)


def _upsample_nearest_exact2d(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT2D")
    in_t, _, out_size, scale = _extract_io_and_params(args, kwargs, expect_out=False)
    out_t = _prepare_out_tensor(in_t, out_size, scale)
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact2d_kernel(
        in_t, out_t, output_size=out_size, scale=scale
    )


def _upsample_nearest_exact2d_out(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT2D_OUT")
    in_t, out_t, out_size, scale = _extract_io_and_params(args, kwargs, expect_out=True)
    if out_t.ndim != 4:
        raise ValueError(
            f"Out tensor must be 4D (N, C, H, W); got shape {tuple(out_t.shape)}"
        )
    # Validate that out_t has the correct computed size if parameters are provided
    expected_h, expected_w = _compute_out_size(
        in_t.shape[-2], in_t.shape[-1], out_size, scale
    )
    if out_t.shape[-2] != expected_h or out_t.shape[-1] != expected_w:
        raise ValueError(
            "Provided out tensor has shape "
            f"{tuple(out_t.shape)} but expected "
            f"({in_t.shape[0]}, {in_t.shape[1]}, {expected_h}, {expected_w})."
        )
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact2d_kernel(
        in_t, out_t, output_size=out_size, scale=scale
    )


def _upsample_nearest_exact2d_vec(*args, **kwargs):
    logger.debug("GEMS _UPSAMPLE_NEAREST_EXACT2D_VEC")
    # Treat vec the same as base variant, allowing list-like output_size/scales
    in_t, _, out_size, scale = _extract_io_and_params(args, kwargs, expect_out=False)
    out_t = _prepare_out_tensor(in_t, out_size, scale)
    if out_t.numel() == 0:
        return out_t
    return _launch_upsample_nearest_exact2d_kernel(
        in_t, out_t, output_size=out_size, scale=scale
    )
