# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Inplace version generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(
    is_tensor=[True, True, True, False], promotion_methods=[(0, 1, 2, "DEFAULT")]
)
@triton.jit
def addcdiv_kernel(x, t1, t2, value):
    return x + value * (t1 / t2)


def addcdiv(inp, tensor1, tensor2, value=1.0):
    """Functional entry; CUDA may dispatch here without hitting ``addcdiv.out``."""
    logger.debug("GEMS ADDCDIV")
    out = torch.empty_like(inp)
    return addcdiv_kernel(inp, tensor1, tensor2, value, out0=out)


def addcdiv_out(inp, tensor1, tensor2, *, value=1.0, out):
    logger.debug("GEMS ADDCDIV_OUT")
    addcdiv_kernel(inp, tensor1, tensor2, value, out0=out)
    return out


def addcdiv_(inp, tensor1, tensor2, value=1.0):
    logger.debug("GEMS ADDCDIV_")
    addcdiv_kernel(inp, tensor1, tensor2, value, out0=inp)
    return inp
