# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def alias(self: torch.Tensor) -> torch.Tensor:
    r"""Return a tensor that shares the same storage as the input.

    This is a view operation that creates a new tensor metadata object
    pointing to the same underlying data. Equivalent to ``self.view(self.shape)``.

    Args:
        self (torch.Tensor): Input tensor.

    Returns:
        torch.Tensor: A new tensor view sharing storage with ``self``.
    """
    logger.debug("GEMS ALIAS")
    # as_strided with same shape/strides/offset creates an alias view
    return self.as_strided(self.shape, self.stride(), self.storage_offset())
