# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def arccosh_func(x):
    # arccosh(x) = log(x + sqrt(x - 1) * sqrt(x + 1))
    x32 = x.to(tl.float32)
    s1 = tl.sqrt(x32 - 1.0)
    s2 = tl.sqrt(x32 + 1.0)
    y32 = tl.log(x32 + s1 * s2)
    return y32.to(x.dtype)


def arccosh_(A):
    logger.debug("GEMS ARCCOSH_")
    arccosh_func(A, out0=A)
    return A
