# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def binary_cross_entropy_with_logits_kernel(x, y):
    # Stable formula:
    # For x >= 0: (1-y)*x + log(1 + exp(-x))
    # For x < 0: (1-y)*(-x) + log(1 + exp(x))
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)
    # This formula is: max(x, 0) - x*y + log(1 + exp(-abs(x)))
    return tl.where(
        x_f32 >= 0,
        x_f32 - x_f32 * y_f32 + tl.log(1.0 + tl.exp(-x_f32)),
        tl.log(1.0 + tl.exp(x_f32)) - x_f32 * y_f32,
    )


@pointwise_dynamic(is_tensor=[True, True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def binary_cross_entropy_with_logits_weight_kernel(x, y, weight):
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)
    w_f32 = weight.to(tl.float32)
    loss = tl.where(
        x_f32 >= 0,
        x_f32 - x_f32 * y_f32 + tl.log(1.0 + tl.exp(-x_f32)),
        tl.log(1.0 + tl.exp(x_f32)) - x_f32 * y_f32,
    )
    return loss * w_f32


@pointwise_dynamic(is_tensor=[True, True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def binary_cross_entropy_with_logits_pos_weight_kernel(x, y, pos_weight):
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)
    pw_f32 = pos_weight.to(tl.float32)
    # Formula for BCE with logits and pos_weight:
    # loss = -(pos_weight * y * log(sigmoid(x)) + (1-y) * log(1 - sigmoid(x)))
    #
    # For y=1: loss = -pos_weight * log(sigmoid(x))
    #   x>=0: -pos_weight * log(1/(1+exp(-x))) = pos_weight * log(1+exp(-x))
    #   x<0: -pos_weight * log(exp(x)/(1+exp(x))) = -pos_weight*x + pos_weight*log(1+exp(x))
    # For y=0: loss = -log(1 - sigmoid(x))
    #   x>=0: -log(exp(-x)/(1+exp(-x))) = x + log(1+exp(-x))
    #   x<0: -log(1/(1+exp(x))) = log(1+exp(x))
    #
    # Combined: y * (x>=0 ? pw*log1p(exp(-x)) : -pw*x + pw*log1p(exp(x))) +
    #           (1-y) * (x>=0 ? x + log1p(exp(-x)) : log1p(exp(x)))
    log_1p_exp_neg_x = tl.log(1.0 + tl.exp(-x_f32))
    log_1p_exp_x = tl.log(1.0 + tl.exp(x_f32))
    x_pos = y_f32 * pw_f32 * log_1p_exp_neg_x + (1.0 - y_f32) * (
        x_f32 + log_1p_exp_neg_x
    )
    x_neg = (
        y_f32 * (-pw_f32 * x_f32 + pw_f32 * log_1p_exp_x) + (1.0 - y_f32) * log_1p_exp_x
    )
    return tl.where(x_f32 >= 0, x_pos, x_neg)


@pointwise_dynamic(
    is_tensor=[True, True, True, True], promotion_methods=[(0, 1, "DEFAULT")]
)
@triton.jit
def binary_cross_entropy_with_logits_weight_pos_weight_kernel(x, y, weight, pos_weight):
    x_f32 = x.to(tl.float32)
    y_f32 = y.to(tl.float32)
    w_f32 = weight.to(tl.float32)
    pw_f32 = pos_weight.to(tl.float32)
    log_1p_exp_neg_x = tl.log(1.0 + tl.exp(-x_f32))
    log_1p_exp_x = tl.log(1.0 + tl.exp(x_f32))
    x_pos = y_f32 * pw_f32 * log_1p_exp_neg_x + (1.0 - y_f32) * (
        x_f32 + log_1p_exp_neg_x
    )
    x_neg = (
        y_f32 * (-pw_f32 * x_f32 + pw_f32 * log_1p_exp_x) + (1.0 - y_f32) * log_1p_exp_x
    )
    loss = tl.where(x_f32 >= 0, x_pos, x_neg)
    return loss * w_f32


def binary_cross_entropy_with_logits(
    self, target, weight=None, pos_weight=None, reduction=1
):
    logger.debug("GEMS BINARY_CROSS_ENTROPY_WITH_LOGITS")

    has_weight = weight is not None
    has_pos_weight = pos_weight is not None

    if has_weight and has_pos_weight:
        out = binary_cross_entropy_with_logits_weight_pos_weight_kernel(
            self, target, weight, pos_weight
        )
    elif has_weight:
        out = binary_cross_entropy_with_logits_weight_kernel(self, target, weight)
    elif has_pos_weight:
        out = binary_cross_entropy_with_logits_pos_weight_kernel(
            self, target, pos_weight
        )
    else:
        out = binary_cross_entropy_with_logits_kernel(self, target)

    # Apply reduction
    # Reduction: 0 = NONE, 1 = MEAN, 2 = SUM
    if reduction == 1:
        return out.mean()
    elif reduction == 2:
        return out.sum()
    else:
        return out


def binary_cross_entropy_with_logits_(
    self, target, weight=None, pos_weight=None, reduction=1
):
    logger.debug("GEMS BINARY_CROSS_ENTROPY_WITH_LOGITS_")

    has_weight = weight is not None
    has_pos_weight = pos_weight is not None

    if has_weight and has_pos_weight:
        out = binary_cross_entropy_with_logits_weight_pos_weight_kernel(
            self, target, weight, pos_weight, out0=self
        )
    elif has_weight:
        out = binary_cross_entropy_with_logits_weight_kernel(
            self, target, weight, out0=self
        )
    elif has_pos_weight:
        out = binary_cross_entropy_with_logits_pos_weight_kernel(
            self, target, pos_weight, out0=self
        )
    else:
        out = binary_cross_entropy_with_logits_kernel(self, target, out0=self)

    # Apply reduction
    if reduction == 1:
        return out.mean()
    elif reduction == 2:
        return out.sum()
    else:
        return out
