# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _cdist_forward_kernel(
    x1_ptr,
    x2_ptr,
    output_ptr,
    P,
    R,
    M,
    batch_size,
    x1_stride_b,
    x1_stride_p,
    x1_stride_m,
    x2_stride_b,
    x2_stride_r,
    x2_stride_m,
    output_stride_b,
    output_stride_p,
    output_stride_r,
    BLOCK_M: tl.constexpr,
):
    """Kernel for computing cdist between two point sets with p=2 (L2 norm).

    x1 shape: (..., P, M) - P points in M-dimensional space
    x2 shape: (..., R, M) - R points in M-dimensional space
    output shape: (..., P, R) - distances between each pair

    Flattened shape: (batch_size, P, M), (batch_size, R, M), (batch_size, P, R)
    """
    # Get program IDs
    pid_p = tle.program_id(0)
    pid_r = tle.program_id(1)
    pid_b = tle.program_id(2)

    # Add batch offset
    x1_ptr_batch = x1_ptr + pid_b * x1_stride_b
    x2_ptr_batch = x2_ptr + pid_b * x2_stride_b
    output_ptr_batch = output_ptr + pid_b * output_stride_b

    # Calculate output position
    output_offset = pid_p * output_stride_p + pid_r * output_stride_r

    # Load point from x1
    x1_offset = pid_p * x1_stride_p
    x1_ptr_row = x1_ptr_batch + x1_offset

    # Load point from x2
    x2_offset = pid_r * x2_stride_r
    x2_ptr_row = x2_ptr_batch + x2_offset

    # Compute L2 distance (p=2)
    acc = tl.zeros([BLOCK_M], dtype=tl.float32)

    # Process in blocks over the feature dimension M
    for m_start in range(0, M, BLOCK_M):
        m_offsets = m_start + tl.arange(0, BLOCK_M)
        m_mask = m_offsets < M

        # Load x1[p, m]
        x1_vals = tl.load(
            x1_ptr_row + m_offsets * x1_stride_m, mask=m_mask, other=0.0
        ).to(tl.float32)

        # Load x2[r, m]
        x2_vals = tl.load(
            x2_ptr_row + m_offsets * x2_stride_m, mask=m_mask, other=0.0
        ).to(tl.float32)

        diff = x1_vals - x2_vals
        acc = acc + diff * diff

    # Finalize: sqrt for L2 norm
    result = tl.sqrt(tl.sum(acc, axis=0))

    # Store result
    tl.store(output_ptr_batch + output_offset, result.to(output_ptr.dtype.element_ty))


def _cdist_forward(
    x1: torch.Tensor, x2: torch.Tensor, p: float = 2.0, compute_mode=None
):
    """Compute the p-norm distance between each pair of the two collections of row vectors.

    Args:
        x1: Input tensor of shape (..., P, M) where P is number of points and M is feature dimension
        x2: Input tensor of shape (..., R, M) where R is number of points and M is feature dimension
        p: p value for the p-norm distance (default: 2.0)
        compute_mode: Computation mode (not used in this implementation)

    Returns:
        Tensor of shape (..., P, R) containing pairwise distances

    Note:
        This implementation only supports p=2.0 (L2 norm). For other p values,
        the function falls back to torch.cdist.
    """
    logger.debug("GEMS CDIST_FORWARD")

    assert x1.dtype in (
        torch.float32,
    ), f"Unsupported dtype '{x1.dtype}'. Only float32 is supported for cdist."

    # Only support p=2.0 for now
    if p != 2.0:
        logger.debug("GEMS CDIST_FORWARD falling back to torch (p != 2.0)")
        return torch.cdist(x1, x2, p=p, compute_mode=compute_mode)

    # Handle broadcasting - get shapes
    x1_shape = x1.shape
    x2_shape = x2.shape

    P = x1_shape[-2]
    R = x2_shape[-2]
    M = x1_shape[-1]

    # Compute broadcast batch shape using PyTorch right-aligned semantics
    batch_dims_x1 = x1_shape[:-2]
    batch_dims_x2 = x2_shape[:-2]
    batch_out = torch.broadcast_shapes(batch_dims_x1, batch_dims_x2)
    batch_size = 1
    for d in batch_out:
        batch_size *= d

    # Broadcast and flatten batch dimensions
    # Right-pad shorter batch dims with leading 1s, then expand to common shape
    x1_expanded = x1.view(
        *([1] * (len(batch_out) - len(batch_dims_x1))), *batch_dims_x1, P, M
    ).expand(*batch_out, P, M)
    x2_expanded = x2.view(
        *([1] * (len(batch_out) - len(batch_dims_x2))), *batch_dims_x2, R, M
    ).expand(*batch_out, R, M)

    x1_flat = x1_expanded.reshape(-1, P, M)
    x2_flat = x2_expanded.reshape(-1, R, M)

    # Create output tensor
    output = torch.empty((batch_size, P, R), dtype=x1.dtype, device=x1.device)

    # Launch kernel
    grid = (P, R, batch_size)

    # Choose BLOCK_M based on M
    BLOCK_M = min(triton.next_power_of_2(M), 64)

    with torch_device_fn.device(x1.device):
        _cdist_forward_kernel[grid](
            x1_flat,
            x2_flat,
            output,
            P,
            R,
            M,
            batch_size,
            x1_flat.stride(0),  # batch stride
            x1_flat.stride(1),  # P stride
            x1_flat.stride(2),  # M stride
            x2_flat.stride(0),  # batch stride
            x2_flat.stride(1),  # R stride
            x2_flat.stride(2),  # M stride
            output.stride(0),  # batch stride
            output.stride(1),  # P stride
            output.stride(2),  # R stride
            BLOCK_M=BLOCK_M,
        )

    # Reshape output to broadcast batch shape
    output = output.view(*batch_out, P, R)

    return output


@libentry()
@triton.jit
def _cdist_backward_kernel(
    grad_ptr,
    x1_ptr,
    x2_ptr,
    cdist_ptr,
    grad_x1_ptr,
    batch_size,
    n1,
    n2,
    dim,
    p,
    BLOCK_N2: tl.constexpr,
    BLOCK_DIM: tl.constexpr,
):
    # Get program ids
    pid_b = tl.program_id(0)
    pid_n1 = tl.program_id(1)
    pid_dim = tl.program_id(2)

    # Offsets for dimension
    off_dim = pid_dim * BLOCK_DIM + tl.arange(0, BLOCK_DIM)
    mask_dim = off_dim < dim

    # This kernel processes one (batch, n1_idx, dim_range) at a time
    # For each dim element, we sum over all n2 elements

    # n1_idx for this program
    n1_idx = pid_n1

    # Accumulator for gradient
    grad_x1_acc = tl.zeros([BLOCK_DIM], dtype=tl.float32)

    # Iterate over n2 dimension (reduction)
    for n2_start in range(0, n2, BLOCK_N2):
        off_n2 = n2_start + tl.arange(0, BLOCK_N2)
        mask_n2 = off_n2 < n2

        # Load x1 for this batch, n1_idx, and dim elements
        # x1[b, n1_idx, d] for all d in off_dim
        x1_offset = pid_b * n1 * dim + n1_idx * dim + off_dim
        x1 = tl.load(x1_ptr + x1_offset, mask=mask_dim, other=0.0).to(tl.float32)

        # Load x2 for this batch, all n2 elements, and dim elements
        # x2[b, n2_j, d] for all n2_j in off_n2, all d in off_dim
        # x2_offset[b, n2_j, d] = b * n2 * dim + n2_j * dim + d
        x2_offset_base = pid_b * n2 * dim
        x2 = tl.load(
            x2_ptr + x2_offset_base + off_n2[:, None] * dim + off_dim[None, :],
            mask=mask_n2[:, None] & mask_dim[None, :],
            other=0.0,
        ).to(tl.float32)

        # Load grad for this batch, n1_idx, and all n2 elements
        # grad[b, n1_idx, n2_j] for all n2_j in off_n2
        grad_offset = pid_b * n1 * n2 + n1_idx * n2 + off_n2
        grad = tl.load(grad_ptr + grad_offset, mask=mask_n2, other=0.0).to(tl.float32)

        # Load cdist for this batch, n1_idx, and all n2 elements
        # cdist[b, n1_idx, n2_j] for all n2_j in off_n2
        cdist = tl.load(cdist_ptr + grad_offset, mask=mask_n2, other=1.0).to(tl.float32)

        # Compute diff: x1[n1_idx, d] - x2[n2_j, d]
        # x1 is [BLOCK_DIM], x2 is [BLOCK_N2, BLOCK_DIM]
        # Need to broadcast x1 across n2 dimension
        diff = x1[None, :] - x2  # [BLOCK_N2, BLOCK_DIM]

        # For p=2, gradient contribution: grad * diff / cdist
        # grad is [BLOCK_N2], cdist is [BLOCK_N2]
        # Need to broadcast grad across dim dimension
        eps = 1e-12
        contrib = grad[:, None] * diff / (cdist[:, None] + eps)  # [BLOCK_N2, BLOCK_DIM]

        # Sum over n2 dimension
        grad_x1_acc += tl.sum(contrib, axis=0)

    # Store result
    store_offset = pid_b * n1 * dim + n1_idx * dim + off_dim
    tl.store(grad_x1_ptr + store_offset, grad_x1_acc, mask=mask_dim)


def _cdist_backward(grad, x1, x2, p, cdist):
    logger.debug("GEMS _cdist_backward")
    assert x1.device == x2.device == grad.device == cdist.device
    assert x1.shape[0] == x2.shape[0] == grad.shape[0] == cdist.shape[0]
    assert x1.shape[2] == x2.shape[2]  # feature dim must match
    assert x1.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
    ), f"Unsupported dtype: {x1.dtype}"

    batch_size, n1, dim = x1.shape
    _, n2, _ = x2.shape

    # Ensure contiguity
    grad = grad.contiguous()
    x1 = x1.contiguous()
    x2 = x2.contiguous()
    cdist = cdist.contiguous()

    grad_x1 = torch.empty_like(x1)

    # For float16/bfloat16, use float32 accumulation
    if x1.dtype in (torch.float16, torch.bfloat16):
        grad_x1_fp32 = torch.empty_like(x1, dtype=torch.float32)
    else:
        grad_x1_fp32 = grad_x1

    BLOCK_N2 = 64
    BLOCK_DIM = 64

    grid = (
        batch_size,
        n1,  # One program per (batch, n1) pair
        triton.cdiv(dim, BLOCK_DIM),
    )

    with torch_device_fn.device(x1.device):
        _cdist_backward_kernel[grid](
            grad,
            x1,
            x2,
            cdist,
            grad_x1_fp32,
            batch_size,
            n1,
            n2,
            dim,
            float(p),
            BLOCK_N2=BLOCK_N2,
            BLOCK_DIM=BLOCK_DIM,
        )

    if x1.dtype in (torch.float16, torch.bfloat16):
        grad_x1 = grad_x1_fp32.to(x1.dtype)
    else:
        grad_x1 = grad_x1_fp32

    return grad_x1
