# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch

logger = logging.getLogger(__name__)


def chunk(A: torch.Tensor, chunks: int, dim: int = 0) -> List[torch.Tensor]:
    r"""Split a tensor into a specific number of chunks.

    The last chunk will be smaller if the tensor size along the given
    dimension is not divisible by :attr:`chunks`.

    Args:
        A (torch.Tensor): Input tensor.
        chunks (int): Number of chunks to produce.
        dim (int): Dimension along which to split the tensor.

    Returns:
        List[torch.Tensor]: List of tensor chunks (views of the original).
    """
    logger.debug("GEMS CHUNK")

    # Handle negative dim
    if dim < 0:
        dim = dim + A.ndim

    # Calculate the size of each chunk (ceiling division)
    dim_size = A.size(dim)
    chunk_size = (dim_size + chunks - 1) // chunks

    # Create list to hold chunks
    result = []

    for i in range(chunks):
        start = i * chunk_size
        end = min(start + chunk_size, dim_size)

        # Stop if this chunk would be empty
        if start >= dim_size:
            break

        # Slice along the target dimension
        slices = [slice(None)] * A.ndim
        slices[dim] = slice(start, end)
        result.append(A[tuple(slices)])

    return result
