# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.copysign import copysign_func

logger = logging.getLogger(__name__)


def copysign_(input, other):
    """In-place copysign: modifies input tensor in place.

    Creates a tensor with the magnitude of input and the sign of other,
    modifying the input tensor in place.
    """
    logger.debug("GEMS COPYSIGN_")
    copysign_func(input, other, out0=input)
    return input
