# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


def make_3d_for_bn(input: Tensor) -> Tensor:
    """
    Converts the input to a 3D view for batch normalization.

    Args:
        input: Input to render 3D.

    Returns:
        Input's 3D view.
    """
    if input.ndim == 2:
        input = input.unsqueeze(-1)

    elif input.ndim >= 4:
        input = input.flatten(2, -1)

    return input


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("batch_norm"),
    key=["batch_dim", "spatial_dim"],
)
@triton.heuristics(runtime.get_heuristic_config("batch_norm"))
@triton.jit
def cudnn_batch_norm_backward_kernel(
    grad_output_pointer,
    input_pointer,
    weight_pointer,
    mean_pointer,
    var_pointer,
    input_grad_pointer,
    weight_grad_pointer,
    bias_grad_pointer,
    batch_dim,
    spatial_dim,
    grad_output_batch_stride,
    grad_output_feat_stride,
    grad_output_spatial_stride,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    input_grad_batch_stride,
    input_grad_feat_stride,
    input_grad_spatial_stride,
    eps,
    input_grad_mask: tl.constexpr,
    weight_grad_mask: tl.constexpr,
    bias_grad_mask: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    feat_pid = tl.program_id(axis=0)

    mean = tl.load(feat_pid + mean_pointer).to(tl.float32)
    var = tl.load(feat_pid + var_pointer).to(tl.float32)
    inv_std = tl_extra_shim.rsqrt(var + eps)

    term1 = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)
    term2 = tl.zeros([BLOCK_M, BLOCK_N], dtype=tl.float32)

    for m_step in range(0, tl.cdiv(batch_dim, BLOCK_M)):
        for n_step in range(0, tl.cdiv(spatial_dim, BLOCK_N)):
            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            curr_grad_output_pointer = (
                grad_output_pointer
                + grad_output_feat_stride * feat_pid
                + grad_output_batch_stride * batch_offset[:, None]
                + grad_output_spatial_stride * spatial_offset[None, :]
            )
            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )

            mask = batch_mask[:, None] & spatial_mask[None, :]
            curr_input = tl.load(curr_input_pointer, mask=mask).to(tl.float32)

            curr_norm = (curr_input - mean) * inv_std
            curr_grad_output = tl.load(curr_grad_output_pointer, mask=mask).to(
                tl.float32
            )

            term1 += curr_norm * curr_grad_output
            term2 += curr_grad_output

    term1 = tl.sum(term1)
    term2 = tl.sum(term2)

    if weight_grad_mask:
        tl.store(feat_pid + weight_grad_pointer, term1)
    if bias_grad_mask:
        tl.store(feat_pid + bias_grad_pointer, term2)

    if not input_grad_mask:
        return

    if weight_pointer:
        weight = tl.load(feat_pid + weight_pointer).to(tl.float32)
    else:
        weight = 1.0

    count = batch_dim * spatial_dim

    for m_step in range(0, tl.cdiv(batch_dim, BLOCK_M)):
        for n_step in range(0, tl.cdiv(spatial_dim, BLOCK_N)):
            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            curr_grad_output_pointer = (
                grad_output_pointer
                + grad_output_feat_stride * feat_pid
                + grad_output_batch_stride * batch_offset[:, None]
                + grad_output_spatial_stride * spatial_offset[None, :]
            )
            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )
            curr_input_grad_pointer = (
                input_grad_pointer
                + input_grad_feat_stride * feat_pid
                + input_grad_batch_stride * batch_offset[:, None]
                + input_grad_spatial_stride * spatial_offset[None, :]
            )

            curr_input = tl.load(
                curr_input_pointer, mask=batch_mask[:, None] & spatial_mask[None, :]
            ).to(tl.float32)
            curr_norm = (curr_input - mean) * inv_std
            curr_grad_output = tl.load(
                curr_grad_output_pointer,
                mask=batch_mask[:, None] & spatial_mask[None, :],
            ).to(tl.float32)
            curr_input_grad = (
                inv_std
                * weight
                * (curr_grad_output - (term1 * curr_norm + term2) / count)
            )
            tl.store(
                curr_input_grad_pointer,
                curr_input_grad,
                mask=batch_mask[:, None] & spatial_mask[None, :],
            )


def cudnn_batch_norm_backward(
    input: Tensor,
    grad_output: Tensor,
    weight: Tensor,
    running_mean: Tensor = None,
    running_var: Tensor = None,
    save_mean: Tensor = None,
    save_var: Tensor = None,
    epsilon: float = 1e-5,
    reserveSpace: Tensor = None,
):
    logger.debug("GEMS CUDNN_BATCH_NORM_BACKWARD")

    input_3d = make_3d_for_bn(input)
    grad_output_3d = make_3d_for_bn(grad_output)

    batch_dim, feat_dim, spatial_dim = input_3d.shape

    # Always compute all gradients
    input_grad = torch.empty_like(input_3d)
    weight_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
    bias_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)

    # Launches 1D grid where each program operates over one feature.
    with torch_device_fn.device(input.device):
        cudnn_batch_norm_backward_kernel[(feat_dim,)](
            grad_output_3d,
            input_3d,
            weight,
            save_mean,
            save_var,  # Pass variance
            input_grad,
            weight_grad,
            bias_grad,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            *input_grad.stride(),
            epsilon,  # eps
            True,  # input_grad_mask
            True,  # weight_grad_mask
            True,  # bias_grad_mask
        )

    return (
        input_grad.view_as(input),
        weight_grad,
        bias_grad,
    )
