# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def scatter_diag_kernel(
    output_ptr,
    src_ptr,
    dim2_size,
    inner_size,
    offset,
    diag_len,
    total_diag_elems,
    BLOCK_SIZE: tl.constexpr,
):
    """Write src values into the diagonal positions of output."""
    pid = tl.program_id(0)
    idx = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = idx < total_diag_elems

    # Decompose linear index into (batch_idx, diag_idx)
    diag_idx = idx % diag_len
    batch_idx = idx // diag_len

    # Compute row, col from diag_idx and offset
    row = tl.where(offset >= 0, diag_idx, diag_idx - offset)
    col = tl.where(offset >= 0, diag_idx + offset, diag_idx)

    # Compute flat output offset
    out_offset = batch_idx * inner_size + row * dim2_size + col

    # Load src value (src is contiguous with shape [batch_size * diag_len])
    src_val = tl.load(src_ptr + idx, mask=mask)

    # Store into output diagonal position
    tl.store(output_ptr + out_offset, src_val, mask=mask)


def diagonal_scatter(input, src, offset=0, dim1=0, dim2=1):
    """Scatter src values into the diagonal of a clone of input.

    Args:
        input: Input tensor (at least 2-D).
        src: Source tensor whose shape matches the diagonal.
        offset: Diagonal offset. 0 for main diagonal, positive for upper,
                negative for lower.
        dim1: First dimension for the 2-D sub-tensor.
        dim2: Second dimension for the 2-D sub-tensor.

    Returns:
        A new tensor with src values scattered along the specified diagonal.
    """
    logger.debug("GEMS DIAGONAL_SCATTER")

    ndim = input.ndim
    # Normalize negative dims
    if dim1 < 0:
        dim1 += ndim
    if dim2 < 0:
        dim2 += ndim

    # Permute so dim1, dim2 become the last two dimensions
    perm = [i for i in range(ndim) if i != dim1 and i != dim2] + [dim1, dim2]
    input_perm = input.permute(perm).contiguous()
    output = input_perm.clone()

    dim1_size = input_perm.shape[-2]
    dim2_size = input_perm.shape[-1]
    batch_size = input_perm.numel() // (dim1_size * dim2_size)

    # Compute diagonal length
    if offset >= 0:
        diag_len = max(0, min(dim1_size, dim2_size - offset))
    else:
        diag_len = max(0, min(dim1_size + offset, dim2_size))

    if diag_len > 0:
        src_flat = src.contiguous().reshape(-1)
        total_diag_elems = batch_size * diag_len
        inner_size = dim1_size * dim2_size
        output_flat = output.reshape(-1)

        BLOCK_SIZE = 1024
        grid = ((total_diag_elems + BLOCK_SIZE - 1) // BLOCK_SIZE,)

        scatter_diag_kernel[grid](
            output_flat,
            src_flat,
            dim2_size,
            inner_size,
            offset,
            diag_len,
            total_diag_elems,
            BLOCK_SIZE=BLOCK_SIZE,
        )

    # Inverse permute back to original layout
    inv_perm = [0] * ndim
    for i, p in enumerate(perm):
        inv_perm[p] = i
    return output.permute(inv_perm).contiguous()
