# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def expand_as(self: torch.Tensor, other: torch.Tensor) -> torch.Tensor:
    r"""Expand this tensor to the same size as ``other``.

    Equivalent to ``self.expand(other.size())``. This is a zero-copy view
    operation that broadcasts dimensions with size 1.

    Args:
        self (torch.Tensor): Input tensor.
        other (torch.Tensor): Tensor whose shape to expand to.

    Returns:
        torch.Tensor: A view of ``self`` expanded to ``other``'s shape.
    """
    logger.debug("GEMS EXPAND_AS")
    return self.expand(other.size())
