# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from functools import reduce
from operator import mul

import torch

logger = logging.getLogger(__name__)


def flatten(self: torch.Tensor, start_dim: int = 0, end_dim: int = -1) -> torch.Tensor:
    r"""Flatten a contiguous range of dimensions into a single dimension.

    Args:
        self (torch.Tensor): Input tensor.
        start_dim (int): First dimension to flatten (default: 0).
        end_dim (int): Last dimension to flatten (default: -1).

    Returns:
        torch.Tensor: A view (or reshape) of the input with the specified
            dimensions flattened into one.
    """
    logger.debug("GEMS FLATTEN")

    ndim = self.ndim

    # Handle 0-d and 1-d tensors
    if ndim == 0:
        return self.reshape(1)
    if ndim == 1:
        return self

    # Normalize negative dims
    if start_dim < 0:
        start_dim += ndim
    if end_dim < 0:
        end_dim += ndim

    # Validation
    if start_dim < 0 or start_dim >= ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-ndim}, {ndim - 1}], but got {start_dim})"
        )
    if end_dim < 0 or end_dim >= ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-ndim}, {ndim - 1}], but got {end_dim})"
        )
    if start_dim > end_dim:
        raise RuntimeError(
            f"flatten() has invalid args: start_dim ({start_dim}) cannot come "
            f"after end_dim ({end_dim})"
        )

    # If start == end, no-op
    if start_dim == end_dim:
        return self

    # Compute the new shape
    shape = list(self.shape)
    flat_size = reduce(mul, shape[start_dim : end_dim + 1], 1)
    new_shape = shape[:start_dim] + [flat_size] + shape[end_dim + 1 :]

    return self.reshape(new_shape)
