# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic
from flag_gems.utils.triton_lang_extension import trunc

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def frac_func(x):
    # frac(x) = x - trunc(x), where trunc(x) is truncation toward zero
    # Convert to float32 for computation to avoid precision issues with bfloat16
    x_fp32 = x.to(tl.float32)
    return (x_fp32 - trunc(x_fp32)).to(x.dtype)


def frac(A):
    logger.debug("GEMS FRAC")
    return frac_func(A)


def frac_(A):
    logger.debug("GEMS FRAC_")
    frac_func(A, out0=A)
    return A
