# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.gcd import _launch_gcd, _materialize_inputs

logger = logging.getLogger(__name__)


def gcd_(A: torch.Tensor, B: torch.Tensor):
    """In-place GCD: A = gcd(A, B), reusing the optimized Binary GCD kernel."""
    logger.debug("GEMS GCD_")
    lhs, rhs, promoted_dtype = _materialize_inputs(A, B)
    # Compute GCD into a flat buffer, then copy back in-place
    flat_out = torch.empty(lhs.numel(), dtype=promoted_dtype, device=A.device)
    _launch_gcd(lhs.reshape(-1), rhs.reshape(-1), flat_out)
    A.copy_(flat_out.view(A.shape))
    return A
