# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
import triton.language.extra.libdevice as libdevice

logger = logging.getLogger(__name__)


@triton.jit
def _ctz(x):
    return libdevice.ffs(x) - 1


@triton.jit
def _binary_gcd(ax, ay, normal, MAX_ITERS: tl.constexpr):
    """Binary GCD (Stein's algorithm) for unsigned inputs.

    Uses a fixed number of iterations (MAX_ITERS) based on the bit width
    of the integer type to avoid unbounded loops on large values.
    """
    zero_ax = ax == 0
    zero_ay = ay == 0
    res = tl.where(zero_ax, ay, ax)
    both_nonzero = normal & (~zero_ax) & (~zero_ay)
    common = _ctz(tl.where(both_nonzero, ax | ay, 1))
    u = tl.where(both_nonzero, ax >> _ctz(tl.where(both_nonzero, ax, 1)), ax)
    v = ay
    active = both_nonzero

    for _ in tl.static_range(MAX_ITERS):
        v_shifted = tl.where(active, v >> _ctz(tl.where(active, v, 1)), v)
        swap = active & (u > v_shifted)
        small = tl.where(swap, v_shifted, u)
        large = tl.where(swap, u, v_shifted)
        u = tl.where(active, small, u)
        v = tl.where(active, large - small, v)
        active = active & (v != 0)

    return tl.where(both_nonzero, u << common, res)


@triton.jit
def lcm_kernel_i32(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)

    ax = tl.abs(x).to(tl.int32)
    ay = tl.abs(y).to(tl.int32)

    # Stein's algorithm worst case is log2(a) + log2(b) iterations.
    # For int32 inputs up to 2^31-1, we need up to 62 iterations.
    gcd_val = _binary_gcd(ax, ay, mask, MAX_ITERS=62)

    # lcm = |x| / gcd * |y| (divide first to reduce overflow chance)
    # When gcd is 0 (both inputs 0), lcm is 0
    # Use unsigned arithmetic to match PyTorch's non-negative result semantics
    safe_gcd = tl.where(gcd_val == 0, 1, gcd_val)
    ax_u = ax.to(tl.uint32)
    ay_u = ay.to(tl.uint32)
    safe_gcd_u = safe_gcd.to(tl.uint32)
    result_u = (ax_u // safe_gcd_u) * ay_u
    result = result_u.to(tl.int32)
    result = tl.where(gcd_val == 0, 0, result)

    tl.store(out_ptr + offsets, result.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_kernel_i64(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)

    ax = tl.abs(x).to(tl.int64)
    ay = tl.abs(y).to(tl.int64)

    # Stein's algorithm worst case is log2(a) + log2(b) iterations.
    # For int64 inputs up to 2^63-1, we need up to 126 iterations.
    gcd_val = _binary_gcd(ax, ay, mask, MAX_ITERS=126)

    safe_gcd = tl.where(gcd_val == 0, 1, gcd_val)
    ax_u = ax.to(tl.uint64)
    ay_u = ay.to(tl.uint64)
    safe_gcd_u = safe_gcd.to(tl.uint64)
    result_u = (ax_u // safe_gcd_u) * ay_u
    result = result_u.to(tl.int64)
    result = tl.where(gcd_val == 0, 0, result)

    tl.store(out_ptr + offsets, result.to(out_ptr.type.element_ty), mask=mask)


def _kernel_meta(dtype):
    if dtype in (torch.int8, torch.int16, torch.int32):
        return lcm_kernel_i32, 512, 4
    if dtype == torch.int64:
        return lcm_kernel_i64, 256, 4
    raise TypeError(f"unsupported dtype for lcm: {dtype}")


def _materialize_inputs(self, other):
    promoted_dtype = torch.promote_types(self.dtype, other.dtype)
    lhs = self if self.dtype == promoted_dtype else self.to(promoted_dtype)
    rhs = other if other.dtype == promoted_dtype else other.to(promoted_dtype)
    lhs, rhs = torch.broadcast_tensors(lhs, rhs)
    return lhs.contiguous(), rhs.contiguous(), promoted_dtype


def lcm(self, other):
    """Compute element-wise least common multiple.

    Uses binary GCD (Stein's algorithm) for efficiency, then derives
    lcm(a, b) = |a| / gcd(a, b) * |b| to avoid intermediate overflow.
    """
    logger.debug("GEMS LCM")
    lhs, rhs, promoted_dtype = _materialize_inputs(self, other)
    result = torch.empty_like(lhs, dtype=promoted_dtype)
    numel = result.numel()
    if numel == 0:
        return result

    kernel, block, num_warps = _kernel_meta(promoted_dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        result.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return result.view(lhs.shape)


def lcm_(self, other):
    """In-place version of lcm."""
    logger.debug("GEMS LCM_")
    result = lcm(self, other)
    self.copy_(result)
    return self
