# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def lift(A):
    """
    Implements aten::lift(Tensor self) -> Tensor

    The lift operation returns the same tensor object with modified autograd
    properties (is_leaf=False, grad_fn=LiftBackward0).

    Since lift is computationally identity (no values change) and requires
    returning the same tensor object with modified autograd metadata,
    this is implemented as a pass-through. The autograd behavior requires
    C++ internals to set grad_fn on existing tensors.

    .. note::
        This implementation returns the input tensor unchanged. It does NOT
        modify autograd metadata (is_leaf, grad_fn) because PyTorch's autograd
        graph manipulation requires C++ internals not accessible from Python.
        For compiled-graph use cases that only need tensor identity semantics,
        this implementation is sufficient.
    """
    logger.debug("GEMS LIFT")
    return A


def lift_out(A, *, out=None):
    """
    Implements aten::lift.out variant - copies A to out and returns out.

    Uses PyTorch's optimized copy_() instead of a Triton kernel for
    cross-backend compatibility and better performance.
    """
    logger.debug("GEMS LIFT_OUT")
    if out is None:
        out = torch.empty_like(A, memory_format=torch.contiguous_format)
    out.copy_(A)
    return out
