# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

from flag_gems.ops.svd import svd

logger = logging.getLogger(__name__)


def linalg_svdvals(A: torch.Tensor, driver: str = None) -> torch.Tensor:
    """Computes the singular values of a matrix.

    Uses the Triton-based SVD implementation to extract singular values only.

    Args:
        A: Input tensor of shape (*, m, n) where * is zero or more batch dimensions.
        driver: Optional cuSOLVER method (forwarded to torch fallback only; the
            Triton SVD kernel does not use cuSOLVER driver selection).

    Returns:
        Singular values in descending order, shape (*, min(m, n)).
    """
    logger.debug("GEMS LINALG_SVDVALS")
    # Only float32 is supported for SVD on CUDA
    assert A.dtype == torch.float32, f"Expected float32, got {A.dtype}"
    if not A.is_contiguous():
        A = A.contiguous()

    try:
        # Use Triton-based SVD to compute singular values only.
        # compute_uv=False avoids unnecessary U/V matrix computation
        # and uses the dedicated singular-values-only kernels
        # (_small_jacobi_svals, _rank2_svals, _blocked_jacobi_pair_svals).
        result = svd(A, some=True, compute_uv=False)
        return result.S
    except NotImplementedError:
        # Fall back to native torch. Use getattr to bypass flag_gems dispatch
        # (which would re-intercept torch.linalg.svdvals → recursion).
        _default_fn = getattr(getattr(torch.ops, "aten"), "linalg_svdvals").default
        return _default_fn(A, driver=driver)
