# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def slogdet_kernel(
    A_input,
    sign_out,
    logabsdet_out,
    LU_out,
    pivots_out,
    n,
    M,
    stride_a,
    stride_sign,
    stride_logabsdet,
    stride_lu,
    BLOCK_SIZE: tl.constexpr,
):
    """
    Compute slogdet for square matrices using Gaussian elimination.
    Each program handles one matrix in the batch.
    """
    # Get the matrix index (batch index)
    pid = tle.program_id(0)

    # Initialize sign to 1.0 and logabsdet to 0.0
    sign = 1.0
    logabsdet = 0.0

    # Get the starting pointer for this matrix
    A_mat = A_input + pid * M * stride_a
    sign_out_mat = sign_out + pid * stride_sign
    logabsdet_out_mat = logabsdet_out + pid * stride_logabsdet
    LU_out_mat = LU_out + pid * stride_lu

    # Gaussian elimination with partial pivoting.
    is_singular = 0
    for k in range(0, n):
        max_row = tl.full((), k, tl.int32)
        pivot = tl.load(A_mat + k * stride_a + k).to(tl.float32)
        max_abs = tl.abs(pivot)

        for i in range(k + 1, n):
            cand = tl.load(A_mat + i * stride_a + k).to(tl.float32)
            cand_abs = tl.abs(cand)
            max_row = tl.where(cand_abs > max_abs, i, max_row)
            max_abs = tl.maximum(max_abs, cand_abs)

        is_singular = tl.where(max_abs <= 1e-10, 1, is_singular)

        if max_abs > 1e-10:
            needs_swap = max_row != k
            for j in range(0, n):
                row_k = tl.load(A_mat + k * stride_a + j)
                row_p = tl.load(A_mat + max_row * stride_a + j)
                tl.store(A_mat + k * stride_a + j, row_p)
                tl.store(A_mat + max_row * stride_a + j, row_k)
            sign = tl.where(needs_swap, -sign, sign)

            pivot = tl.load(A_mat + k * stride_a + k).to(tl.float32)
            for i in range(k + 1, n):
                a_ik = tl.load(A_mat + i * stride_a + k).to(tl.float32)
                factor = a_ik / pivot
                tl.store(A_mat + i * stride_a + k, factor.to(A_mat.dtype.element_ty))

                for j in range(k + 1, n):
                    a_ij = tl.load(A_mat + i * stride_a + j).to(tl.float32)
                    a_kj = tl.load(A_mat + k * stride_a + j).to(tl.float32)
                    new_val = a_ij - factor * a_kj
                    tl.store(
                        A_mat + i * stride_a + j,
                        new_val.to(A_mat.dtype.element_ty),
                    )
    # Compute logabsdet from diagonal elements
    for i in range(n):
        diag = tl.load(A_mat + i * stride_a + i).to(tl.float32)
        diag_abs = tl.abs(diag)

        # Handle near-zero diagonal elements (singular matrix)
        diag_is_zero = diag_abs < 1e-10
        is_singular = tl.where(diag_is_zero, 1, is_singular)
        diag_abs = tl.where(diag_is_zero, 1.0, diag_abs)

        # Update sign based on diagonal element
        diag_sign = tl.where(diag > 0, 1.0, tl.where(diag < 0, -1.0, 0.0))
        sign = sign * diag_sign

        # Add to logabsdet
        logabsdet = logabsdet + tl.log(diag_abs)

    sign = tl.where(is_singular != 0, 0.0, sign)
    logabsdet = tl.where(is_singular != 0, -float("inf"), logabsdet)

    # Copy the LU decomposition to output
    for i in range(n):
        for j in range(n):
            val = tl.load(A_mat + i * stride_a + j)
            tl.store(LU_out_mat + i * stride_lu + j, val)

    # Store results
    tl.store(sign_out_mat, sign.to(sign_out_mat.dtype.element_ty))
    tl.store(logabsdet_out_mat, logabsdet.to(logabsdet_out_mat.dtype.element_ty))


def slogdet(A):
    """
    Compute the sign and natural logarithm of the absolute value of the determinant
    of a square matrix.

    Args:
        A: tensor of shape (*, n, n) where * is zero or more batch dimensions.

    Returns:
        A tuple (sign, logabsdet, LU, pivots) where:
        - sign has the same dtype as A
        - logabsdet is always real-valued
        - LU is the LU decomposition
        - pivots is the pivot indices (not computed in this implementation)
    """
    assert A.dim() >= 2, "Input must be at least 2D"
    assert A.shape[-1] == A.shape[-2], "Input must be square"
    # The generated slogdet kernel uses float32 arithmetic; reject unsupported dtypes explicitly.
    assert (
        A.dtype == torch.float32
    ), f"slogdet: unsupported dtype {A.dtype}, expected float32"

    batch_shape = A.shape[:-2]
    n = A.shape[-1]
    batch_size = 1
    for dim in batch_shape:
        batch_size *= dim

    # Output tensors
    sign = torch.empty(batch_shape, dtype=A.dtype, device=A.device)
    logabsdet = torch.empty(batch_shape, dtype=A.dtype, device=A.device)
    LU = torch.empty(A.shape, dtype=A.dtype, device=A.device)
    # pivots is not computed in this implementation, return a dummy tensor
    pivots = torch.empty(batch_shape, dtype=torch.int32, device=A.device)

    # Handle empty batch
    if batch_size == 0:
        return (
            torch.zeros_like(sign),
            torch.full_like(logabsdet, float("-inf")),
            torch.empty_like(LU),
            torch.zeros_like(pivots),
        )

    # Make a copy of input to avoid modifying the original
    A_copy = A.clone()

    # Get stride for batch
    stride_a = A_copy.stride(-2)
    stride_sign = sign.stride(-1) if sign.dim() > 0 else 0
    stride_logabsdet = logabsdet.stride(-1) if logabsdet.dim() > 0 else 0
    stride_lu = LU.stride(-2)

    # Launch kernel
    grid = (batch_size,)

    # Choose block size based on matrix size
    block_size = 32 if n <= 32 else 64

    with torch_device_fn.device(A.device):
        slogdet_kernel[grid](
            A_copy,
            sign,
            logabsdet,
            LU,
            pivots,
            n,
            A_copy.shape[-2],
            stride_a,
            stride_sign,
            stride_logabsdet,
            stride_lu,
            block_size,
        )

    return sign, logabsdet, LU, pivots


# Wrapper for use with torch.linalg.slogdet interface
def linalg_slogdet(A):
    """Return the sign and log absolute determinant of a square matrix."""
    logger.debug("GEMS LINALG_SLOGDET")
    assert A.dtype == torch.float32
    sign, logabsdet, _lu, _pivots = slogdet(A)
    return sign, logabsdet
