# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Define a fixed maximum matrix size we can handle
MAX_MATRIX_SIZE = 64


@libentry()
@triton.jit
def ldl_factor_kernel(
    A,
    LD,
    pivots,
    N,
    stride_a0,
    stride_a1,
    stride_a2,
    stride_ld0,
    stride_ld1,
    stride_ld2,
    MAX_SIZE: tl.constexpr,
):
    # Each program handles one matrix in the batch
    batch_idx = tl.program_id(0)

    # Use a single thread to do the sequential LDL factorization
    if tl.program_id(1) == 0:
        # Load the entire matrix into LD
        for i in range(MAX_SIZE):
            row_start = A + batch_idx * stride_a0 + i * stride_a1
            row = tl.load(row_start + tl.arange(0, MAX_SIZE) * stride_a2, mask=(i < N))
            ld_row_start = LD + batch_idx * stride_ld0 + i * stride_ld1
            tl.store(
                ld_row_start + tl.arange(0, MAX_SIZE) * stride_ld2, row, mask=(i < N)
            )

        # Compute the LDL factorization
        # Output format (PyTorch style):
        # - Diagonal LD[k,k] = D[k,k]
        # - Below diagonal LD[i,k] = L[i,k] for i > k
        #
        # Algorithm:
        # For k = 0 to n-1:
        #   D[k,k] = LD[k,k] - sum(L[k,j]^2 * D[j,j]) for j < k
        #   For i = k+1 to n-1:
        #     L[i,k] = (LD[i,k] - sum(L[i,j] * L[k,j] * D[j,j]) for j < k) / D[k,k]

        # k loop
        k = 0
        while k < N:
            # Get D[k,k] - it's at LD[k,k]
            d_kk = tl.load(
                LD + batch_idx * stride_ld0 + k * stride_ld1 + k * stride_ld2
            )

            # j loop for computing D[k,k]
            # D[k,k] = LD[k,k] - sum(L[k,j]^2 * D[j,j]) for j < k
            # In our format: LD[k,j] = L[k,j] for j < k (below diagonal)
            j = 0
            while j < k:
                d_jj = tl.load(
                    LD + batch_idx * stride_ld0 + j * stride_ld1 + j * stride_ld2
                )
                l_kj = tl.load(
                    LD + batch_idx * stride_ld0 + k * stride_ld1 + j * stride_ld2
                )
                # D[k,k] -= L[k,j]^2 * D[j,j]
                d_kk = d_kk - (l_kj * l_kj) * d_jj
                j = j + 1

            # Store D[k,k]
            tl.store(
                LD + batch_idx * stride_ld0 + k * stride_ld1 + k * stride_ld2, d_kk
            )

            # Zero out elements above diagonal in column k
            i_zero = 0
            while i_zero < k:
                tl.store(
                    LD + batch_idx * stride_ld0 + i_zero * stride_ld1 + k * stride_ld2,
                    0.0,
                )
                i_zero = i_zero + 1

            # i loop for computing L[i,k]
            # L[i,k] = (LD[i,k] - sum(L[i,j] * L[k,j] * D[j,j]) for j < k) / D[k,k]
            i = k + 1
            while i < N:
                l_ik = tl.load(
                    LD + batch_idx * stride_ld0 + i * stride_ld1 + k * stride_ld2
                )

                # j loop
                j_inner = 0
                while j_inner < k:
                    d_jj = tl.load(
                        LD
                        + batch_idx * stride_ld0
                        + j_inner * stride_ld1
                        + j_inner * stride_ld2
                    )
                    l_ij = tl.load(
                        LD
                        + batch_idx * stride_ld0
                        + i * stride_ld1
                        + j_inner * stride_ld2
                    )
                    l_kj = tl.load(
                        LD
                        + batch_idx * stride_ld0
                        + k * stride_ld1
                        + j_inner * stride_ld2
                    )
                    # L[i,k] -= L[i,j] * L[k,j] * D[j,j]
                    l_ik = l_ik - (l_ij * l_kj) * d_jj
                    j_inner = j_inner + 1

                # Divide by D[k,k] to get L[i,k]
                l_ik = l_ik / d_kk
                # Store L[i,k] (not L[i,k] * D[k,k])
                tl.store(
                    LD + batch_idx * stride_ld0 + i * stride_ld1 + k * stride_ld2, l_ik
                )
                i = i + 1

            k = k + 1

        # Zero out upper triangular part (i < j)
        j = 0
        while j < N:
            i = 0
            while i < j:
                tl.store(
                    LD + batch_idx * stride_ld0 + i * stride_ld1 + j * stride_ld2, 0.0
                )
                i = i + 1
            j = j + 1

        # Store pivots
        for i in range(MAX_SIZE):
            pivots_ptr = pivots + batch_idx * N + i
            tl.store(pivots_ptr, i + 1, mask=(i < N))


def ldl_factor(A, *, hermitian=False):
    """
    Compute the LDL factorization of a symmetric/hermitian matrix.

    Returns a named tuple (LD, pivots) where:
    - LD is a compact representation of L and D matrices
    - pivots contains the pivot indices (1-indexed)

    This implements the standard LDL decomposition: A = L @ D @ L^T
    where L is unit lower triangular and D is diagonal.
    """
    if A.ndim < 2:
        raise ValueError("linalg_ldl_factor: A must be at least 2D")

    if A.shape[-2] != A.shape[-1]:
        raise ValueError("linalg_ldl_factor: matrix must be square")

    if A.dtype not in (torch.float32, torch.float64):
        raise TypeError("linalg_ldl_factor: only float32 and float64 are supported")

    batch_shape = A.shape[:-2]
    n = A.shape[-1]

    if n > MAX_MATRIX_SIZE:
        raise ValueError(
            f"linalg_ldl_factor: matrix size {n} exceeds maximum {MAX_MATRIX_SIZE}"
        )

    # Ensure symmetric input (required for LDL factorization)
    if hermitian:
        A_sym = (A + A.transpose(-2, -1).conj()) / 2
    else:
        A_sym = (A + A.transpose(-2, -1)) / 2

    A_sym = A_sym.contiguous()

    LD = torch.empty_like(A_sym)
    pivots_shape = batch_shape + (n,)
    pivots = torch.empty(pivots_shape, dtype=torch.int32, device=A.device)

    logger.debug(
        "GEMS LDL_FACTOR, shape: %s, n: %d, hermitian: %s",
        A_sym.shape,
        n,
        hermitian,
    )

    batch_size = 1
    for dim in batch_shape:
        batch_size *= dim

    grid = (batch_size, 1)

    with torch_device_fn.device(A.device):
        ldl_factor_kernel[grid](
            A_sym,
            LD,
            pivots,
            n,
            A_sym.stride(0) if A_sym.ndim > 2 else 0,
            A_sym.stride(-2),
            A_sym.stride(-1),
            LD.stride(0) if LD.ndim > 2 else 0,
            LD.stride(-2),
            LD.stride(-1),
            MAX_MATRIX_SIZE,
            num_warps=1,
        )

    # Return as a named tuple manually
    return (LD, pivots)
