# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

import flag_gems

from .mm import mm
from .sum import sum_dim

logger = logging.getLogger(__name__)


def linear_backward(
    input: torch.Tensor,
    grad_output: torch.Tensor,
    weight: torch.Tensor,
    output_mask: tuple,
):
    """
    Computes the gradients for a linear layer backward pass.

    Args:
        input: Input tensor of shape (*, in_features)
        grad_output: Gradient of output of shape (*, out_features)
        weight: Weight tensor of shape (out_features, in_features)
        output_mask: Tuple of 3 booleans (grad_input, grad_weight, grad_bias)

    Returns:
        Tuple of (grad_input, grad_weight, grad_bias), where each element is None
        if the corresponding mask is False
    """
    logger.debug("GEMS LINEAR_BACKWARD")

    # Validate inputs
    assert (
        input.device.type == flag_gems.device
        and grad_output.device.type == flag_gems.device
        and weight.device.type == flag_gems.device
    )
    assert input.device == grad_output.device == weight.device

    # Handle output_mask - ensure it's a tuple
    if not isinstance(output_mask, (tuple, list)):
        output_mask = (output_mask[0], output_mask[1], output_mask[2])

    input_shape = input.shape
    weight_shape = weight.shape
    out_features = weight_shape[0]
    in_features = weight_shape[1]

    # Get batch dimensions (all but the last dim which is features)
    batch_dims = input_shape[:-1]
    batch_size = 1
    for dim in batch_dims:
        batch_size *= dim

    # Flatten batch dimensions
    input_flat = input.view(batch_size, in_features).contiguous()
    grad_output_flat = grad_output.view(batch_size, out_features).contiguous()

    grad_input = None
    grad_weight = None
    grad_bias = None

    # grad_input = grad_output @ weight
    # Shape: (batch, out_features) @ (out_features, in_features) = (batch, in_features)
    if output_mask[0]:
        if input.dtype == torch.float16:
            grad_input = mm(
                grad_output_flat.to(torch.float32), weight.to(torch.float32)
            )
            grad_input = grad_input.view(*batch_dims, in_features).to(input.dtype)
        else:
            grad_input = mm(grad_output_flat, weight)
            grad_input = grad_input.view(*batch_dims, in_features)

    # grad_weight = grad_output.T @ input
    # Shape: (out_features, batch) @ (batch, in_features) = (out_features, in_features)
    if output_mask[1]:
        grad_output_T = grad_output_flat.t().contiguous()
        if weight.dtype == torch.float16:
            grad_weight = mm(
                grad_output_T.to(torch.float32), input_flat.to(torch.float32)
            )
            grad_weight = grad_weight.to(weight.dtype)
        else:
            grad_weight = mm(grad_output_T, input_flat)

    # grad_bias = grad_output.sum(dim=0)
    # Shape: (batch, out_features) -> (out_features,)
    if output_mask[2]:
        if weight.dtype == torch.float16:
            grad_bias = sum_dim(grad_output_flat.to(torch.float32), dim=(0,)).to(
                weight.dtype
            )
        else:
            grad_bias = sum_dim(grad_output_flat, dim=(0,))

    return grad_input, grad_weight, grad_bias
