# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def log_sigmoid_forward_kernel(
    x_ptr, buffer_ptr, output_ptr, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)

    # log_sigmoid(x) = log(sigmoid(x)) = -log(1 + exp(-x))
    # Using the stable formula: log_sigmoid(x) = min(x, 0) - log(1 + exp(-|x|))
    x_f32 = x.to(tl.float32)
    log_sigmoid_val = tl.minimum(x_f32, 0.0) - tl.log(1.0 + tl.exp(-tl.abs(x_f32)))

    # Compute buffer for backward: exp(-|x|)
    # This is used in backward: sigmoid(-x) = buffer / (1 + buffer)
    abs_x = tl.abs(x_f32)
    buffer_val = tl.exp(-abs_x)

    tl.store(output_ptr + offsets, log_sigmoid_val.to(x.dtype), mask=mask)
    tl.store(buffer_ptr + offsets, buffer_val.to(x.dtype), mask=mask)


def log_sigmoid_forward(A):
    logger.debug("GEMS LOG_SIGMOID_FORWARD")
    output = torch.empty_like(A)
    buffer = torch.empty_like(A)

    # Reshape to 1D for the kernel
    A_flat = A.reshape(-1)
    output_flat = output.reshape(-1)
    buffer_flat = buffer.reshape(-1)

    n_elements = A_flat.numel()
    # 1024 provides good occupancy for element-wise log_sigmoid_forward kernel
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(n_elements, BLOCK_SIZE),)

    log_sigmoid_forward_kernel[grid](
        A_flat,
        buffer_flat,
        output_flat,
        n_elements,
        BLOCK_SIZE,
    )

    return output, buffer
