# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

_SUPPORTED_DTYPES = (torch.float16, torch.bfloat16, torch.float32, torch.float64)


@triton.jit
def log_kernel_(x_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)
    y_f32 = tl.log(x_f32)
    y = y_f32.to(x.dtype)
    tl.store(x_ptr + offsets, y, mask=mask)


def log_(*args, **kwargs):
    logger.debug("GEMS LOG_")
    x = args[0] if len(args) > 0 else kwargs.get("input", None)

    if x is None:
        raise ValueError(
            "log_ expects a tensor as the first argument or keyword 'input'."
        )
    if not isinstance(x, torch.Tensor):
        raise TypeError("log_ expects a torch.Tensor as input.")

    if x.dtype not in _SUPPORTED_DTYPES:
        # The Triton kernel only handles real floating-point dtypes. For anything
        # else (e.g. integer tensors), an in-place log cannot store the float
        # result, so raise instead of silently truncating -- matching torch, which
        # errors on int32.log_() and similar. We raise directly rather than
        # delegating to torch.ops.aten.log_, which would recurse back into this
        # patched op while gems is active.
        raise TypeError(f"log_ does not support dtype {x.dtype}")

    # Handle non-contiguous tensors by operating on a contiguous copy and copying back
    if not x.is_contiguous():
        y = x.contiguous()
        n_elements = y.numel()
        if n_elements == 0:
            return x
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(y.device):
            log_kernel_[grid](y, n_elements, BLOCK_SIZE=1024)
        x.copy_(y)
        return x

    n_elements = x.numel()
    if n_elements == 0:
        return x

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        log_kernel_[grid](x, n_elements, BLOCK_SIZE=1024)
    return x
