# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import functools
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import device, torch_device_fn
from flag_gems.utils import get_device_properties, libentry
from flag_gems.utils import triton_lang_extension as tle

device = device.name
logger = logging.getLogger(__name__)


@functools.lru_cache
def get_num_sms(idx: int) -> int:
    return get_device_properties(idx).multi_processor_count


@libentry()
@triton.jit
def logcumsumexp_kernel(inp, out, M, N, BLOCK_SIZE: tl.constexpr):
    """Persistent kernel for logcumsumexp - works for K==1 case (row scan)"""
    pid_m = tle.program_id(0)
    row_offset = pid_m * N

    # Load the entire row
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = offsets < N
    x = tl.load(inp + row_offset + offsets, mask=mask, other=float("-inf")).to(
        tl.float32
    )

    # Compute logcumsumexp using cumsum with numerical stability
    # logcumsumexp[i] = log(sum_{j=0}^{i} exp(x[j]))
    # For stability: subtract max first
    row_max = tl.max(x)
    x_shifted = tl.exp(x - row_max)
    cumsum_exp = tl.cumsum(x_shifted, axis=0)
    result = row_max + tl.log(cumsum_exp)

    tl.store(out + row_offset + offsets, result, mask=mask)


def logcumsumexp_wrapper(inp, dim=1, dtype=None, out=None):
    assert dim >= -inp.ndim and dim < inp.ndim, "Invalid dim"
    shape = inp.shape
    dim = dim % inp.ndim
    M = 1
    N = shape[dim]
    for i in range(dim):
        M *= shape[i]
    inp = inp.contiguous()
    K = inp.numel() // M // N

    if dtype is None:
        dtype = inp.dtype
        if (
            dtype in (torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64)
            or dtype == torch.bool
        ):
            dtype = torch.float32
    if out is None:
        out = torch.empty_like(inp, dtype=dtype)

    with torch_device_fn.device(inp.device):
        if K == 1:  # row scan
            TILE_SIZE = triton.next_power_of_2(N)
            # Use more warps for wider rows to keep occupancy up on long scans.
            num_warps = 8 if TILE_SIZE > 2048 else 4
            logcumsumexp_kernel[(M, 1, 1)](
                inp, out, M, N, TILE_SIZE, num_warps=num_warps
            )
        else:  # column scan (K > 1)
            # For K > 1, each of the M*K rows is independent
            # We scan along dimension N (dim), and K becomes the "batch" dimension
            # Layout: (M, N, K) -> treat as (M*K, N) with K as batch
            # Actually for simplicity, let's handle the K > 1 case with a different approach
            # by processing each (M, K) combination independently
            TILE_SIZE = triton.next_power_of_2(N)
            # Use more warps for wider rows to keep occupancy up on long scans.
            num_warps = 8 if TILE_SIZE > 2048 else 4
            # Grid: (M, K, 1) to process each (m, k) pair independently
            logcumsumexp_kernel_3d[(M, K, 1)](
                inp, out, M, N, K, TILE_SIZE, num_warps=num_warps
            )

    return out


@libentry()
@triton.jit
def logcumsumexp_kernel_3d(inp, out, M, N, K, BLOCK_SIZE: tl.constexpr):
    """Kernel for logcumsumexp when K > 1"""
    pid_m = tle.program_id(0)
    pid_k = tle.program_id(1)

    # Calculate offset for this (m, k) row
    # Input shape: (M, N, K) when dim=1
    # Element (m, n, k) is at offset m*N*K + n*K + k
    # For fixed (m, k), elements at n=0,1,2,... are at offsets:
    #   m*N*K + k, m*N*K + K + k, m*N*K + 2*K + k, ...
    # So base offset is m*N*K + k, stride is K
    row_offset = pid_m * N * K + pid_k

    # Load the row with stride K
    offsets = tl.arange(0, BLOCK_SIZE) * K
    mask = offsets < N * K
    # Use pointer arithmetic: inp + row_offset + n*K = inp + row_offset + offsets
    x = tl.load(inp + row_offset + offsets, mask=mask, other=float("-inf")).to(
        tl.float32
    )

    # Compute logcumsumexp
    row_max = tl.max(x)
    x_shifted = tl.exp(x - row_max)
    cumsum_exp = tl.cumsum(x_shifted, axis=0)
    result = row_max + tl.log(cumsum_exp)

    # Store result
    tl.store(out + row_offset + offsets, result, mask=mask)


def logcumsumexp(inp, dim=1, *, dtype=None):
    logger.debug("GEMS LOGCUMSUMEXP")
    return logcumsumexp_wrapper(inp, dim, dtype)


def logcumsumexp_out(inp, dim=1, *, dtype=None, out):
    logger.debug("GEMS LOGCUMSUMEXP_OUT")
    return logcumsumexp_wrapper(inp, dim, dtype, out)
