# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.dropout import dropout as _dropout
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Small recurrent shapes dominate this operator in the benchmark suite. These
# block sizes keep register use controlled while still covering common hidden
# sizes with one or two programs.
_BLOCK_B = 8
_BLOCK_H_MAX = 32
_BLOCK_K_MAX = 64
_COPY_BLOCK = 1024


@libentry()
@triton.jit
def _copy_hx_slice_kernel(
    src,
    dst,
    state_idx,
    batch_size,
    hidden_size,
    src_stride_0,
    src_stride_1,
    src_stride_2,
    BLOCK: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < batch_size * hidden_size
    batch_offsets = offsets // hidden_size
    hidden_offsets = offsets - batch_offsets * hidden_size
    src_offsets = (
        state_idx * src_stride_0
        + batch_offsets * src_stride_1
        + hidden_offsets * src_stride_2
    )
    values = tl.load(src + src_offsets, mask=mask, other=0.0)
    tl.store(dst + offsets, values, mask=mask)


@libentry()
@triton.jit
def _store_hx_slice_kernel(
    src,
    dst,
    state_idx,
    batch_size,
    hidden_size,
    dst_stride_0,
    dst_stride_1,
    dst_stride_2,
    BLOCK: tl.constexpr,
):
    offsets = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < batch_size * hidden_size
    batch_offsets = offsets // hidden_size
    hidden_offsets = offsets - batch_offsets * hidden_size
    dst_offsets = (
        state_idx * dst_stride_0
        + batch_offsets * dst_stride_1
        + hidden_offsets * dst_stride_2
    )
    values = tl.load(src + offsets, mask=mask, other=0.0)
    tl.store(dst + dst_offsets, values, mask=mask)


@libentry()
@triton.jit
def _lstm_step_kernel(
    x_ptr,
    h_prev_ptr,
    c_prev_ptr,
    w_ih_ptr,
    w_hh_ptr,
    b_ih_ptr,
    b_hh_ptr,
    h_next_ptr,
    c_next_ptr,
    out_ptr,
    seq_idx,
    out_feature_offset,
    input_size,
    hidden_size,
    batch_size,
    x_stride_s,
    x_stride_b,
    x_stride_f,
    w_ih_stride_r,
    w_ih_stride_c,
    w_hh_stride_r,
    w_hh_stride_c,
    b_ih_stride,
    b_hh_stride,
    out_stride_s,
    out_stride_b,
    out_stride_f,
    HAS_BIAS: tl.constexpr,
    BLOCK_B: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_b = tl.program_id(0)
    pid_h = tl.program_id(1)
    offs_b = pid_b * BLOCK_B + tl.arange(0, BLOCK_B)
    offs_h = pid_h * BLOCK_H + tl.arange(0, BLOCK_H)
    bh_mask = (offs_b[:, None] < batch_size) & (offs_h[None, :] < hidden_size)

    i_acc = tl.zeros((BLOCK_B, BLOCK_H), dtype=tl.float32)
    f_acc = tl.zeros((BLOCK_B, BLOCK_H), dtype=tl.float32)
    g_acc = tl.zeros((BLOCK_B, BLOCK_H), dtype=tl.float32)
    o_acc = tl.zeros((BLOCK_B, BLOCK_H), dtype=tl.float32)

    for k_block in range(0, tl.cdiv(input_size, BLOCK_K)):
        offs_k = k_block * BLOCK_K + tl.arange(0, BLOCK_K)
        x_offsets = (
            seq_idx * x_stride_s
            + offs_b[:, None] * x_stride_b
            + offs_k[None, :] * x_stride_f
        )
        x = tl.load(
            x_ptr + x_offsets,
            mask=(offs_b[:, None] < batch_size) & (offs_k[None, :] < input_size),
            other=0.0,
        )

        w_i = tl.load(
            w_ih_ptr
            + (offs_h[None, :]) * w_ih_stride_r
            + offs_k[:, None] * w_ih_stride_c,
            mask=(offs_k[:, None] < input_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_f = tl.load(
            w_ih_ptr
            + (hidden_size + offs_h[None, :]) * w_ih_stride_r
            + offs_k[:, None] * w_ih_stride_c,
            mask=(offs_k[:, None] < input_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_g = tl.load(
            w_ih_ptr
            + (2 * hidden_size + offs_h[None, :]) * w_ih_stride_r
            + offs_k[:, None] * w_ih_stride_c,
            mask=(offs_k[:, None] < input_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_o = tl.load(
            w_ih_ptr
            + (3 * hidden_size + offs_h[None, :]) * w_ih_stride_r
            + offs_k[:, None] * w_ih_stride_c,
            mask=(offs_k[:, None] < input_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        i_acc += tl.dot(x, w_i, out_dtype=tl.float32, allow_tf32=False)
        f_acc += tl.dot(x, w_f, out_dtype=tl.float32, allow_tf32=False)
        g_acc += tl.dot(x, w_g, out_dtype=tl.float32, allow_tf32=False)
        o_acc += tl.dot(x, w_o, out_dtype=tl.float32, allow_tf32=False)

    for k_block in range(0, tl.cdiv(hidden_size, BLOCK_K)):
        offs_k = k_block * BLOCK_K + tl.arange(0, BLOCK_K)
        h = tl.load(
            h_prev_ptr + offs_b[:, None] * hidden_size + offs_k[None, :],
            mask=(offs_b[:, None] < batch_size) & (offs_k[None, :] < hidden_size),
            other=0.0,
        )

        w_i = tl.load(
            w_hh_ptr
            + (offs_h[None, :]) * w_hh_stride_r
            + offs_k[:, None] * w_hh_stride_c,
            mask=(offs_k[:, None] < hidden_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_f = tl.load(
            w_hh_ptr
            + (hidden_size + offs_h[None, :]) * w_hh_stride_r
            + offs_k[:, None] * w_hh_stride_c,
            mask=(offs_k[:, None] < hidden_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_g = tl.load(
            w_hh_ptr
            + (2 * hidden_size + offs_h[None, :]) * w_hh_stride_r
            + offs_k[:, None] * w_hh_stride_c,
            mask=(offs_k[:, None] < hidden_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        w_o = tl.load(
            w_hh_ptr
            + (3 * hidden_size + offs_h[None, :]) * w_hh_stride_r
            + offs_k[:, None] * w_hh_stride_c,
            mask=(offs_k[:, None] < hidden_size) & (offs_h[None, :] < hidden_size),
            other=0.0,
        )
        i_acc += tl.dot(h, w_i, out_dtype=tl.float32, allow_tf32=False)
        f_acc += tl.dot(h, w_f, out_dtype=tl.float32, allow_tf32=False)
        g_acc += tl.dot(h, w_g, out_dtype=tl.float32, allow_tf32=False)
        o_acc += tl.dot(h, w_o, out_dtype=tl.float32, allow_tf32=False)

    if HAS_BIAS:
        bias_i = tl.load(
            b_ih_ptr + offs_h * b_ih_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_i += tl.load(
            b_hh_ptr + offs_h * b_hh_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_f = tl.load(
            b_ih_ptr + (hidden_size + offs_h) * b_ih_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_f += tl.load(
            b_hh_ptr + (hidden_size + offs_h) * b_hh_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_g = tl.load(
            b_ih_ptr + (2 * hidden_size + offs_h) * b_ih_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_g += tl.load(
            b_hh_ptr + (2 * hidden_size + offs_h) * b_hh_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_o = tl.load(
            b_ih_ptr + (3 * hidden_size + offs_h) * b_ih_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        bias_o += tl.load(
            b_hh_ptr + (3 * hidden_size + offs_h) * b_hh_stride,
            mask=offs_h < hidden_size,
            other=0.0,
        )
        i_acc += bias_i[None, :]
        f_acc += bias_f[None, :]
        g_acc += bias_g[None, :]
        o_acc += bias_o[None, :]

    log2e: tl.constexpr = 1.4426950408889634
    i_gate = 1.0 / (1.0 + tl.exp2(-i_acc * log2e))
    f_gate = 1.0 / (1.0 + tl.exp2(-f_acc * log2e))
    g_gate = 2.0 / (1.0 + tl.exp2(-2.0 * g_acc * log2e)) - 1.0
    o_gate = 1.0 / (1.0 + tl.exp2(-o_acc * log2e))

    c_prev = tl.load(
        c_prev_ptr + offs_b[:, None] * hidden_size + offs_h[None, :],
        mask=bh_mask,
        other=0.0,
    ).to(tl.float32)
    c_next = f_gate * c_prev + i_gate * g_gate
    h_next = o_gate * (2.0 / (1.0 + tl.exp2(-2.0 * c_next * log2e)) - 1.0)

    state_offsets = offs_b[:, None] * hidden_size + offs_h[None, :]
    out_offsets = (
        seq_idx * out_stride_s
        + offs_b[:, None] * out_stride_b
        + (out_feature_offset + offs_h[None, :]) * out_stride_f
    )
    tl.store(h_next_ptr + state_offsets, h_next, mask=bh_mask)
    tl.store(c_next_ptr + state_offsets, c_next, mask=bh_mask)
    tl.store(out_ptr + out_offsets, h_next, mask=bh_mask)


def _ceil_power_of_2(value: int) -> int:
    return 1 << (value - 1).bit_length()


def _block_size(value: int, maximum: int) -> int:
    return min(max(_ceil_power_of_2(value), 16), maximum)


def _matrix_strides(tensor: torch.Tensor, rows: int, cols: int):
    if tensor.numel() != rows * cols:
        raise RuntimeError(
            f"invalid LSTM weight with {tensor.numel()} elements, expected {rows * cols}"
        )
    if tensor.dim() == 2:
        if tensor.shape != (rows, cols):
            raise RuntimeError(
                f"invalid LSTM weight shape {tuple(tensor.shape)}, expected {(rows, cols)}"
            )
        return tensor.stride(0), tensor.stride(1)
    if tensor.dim() == 1:
        return cols, 1
    raise RuntimeError(f"LSTM weights must be 1-D or 2-D, got {tensor.dim()}-D")


def _bias_stride(tensor: torch.Tensor, size: int) -> int:
    if tensor.numel() != size:
        raise RuntimeError(
            f"invalid LSTM bias with {tensor.numel()} elements, expected {size}"
        )
    if tensor.dim() == 1:
        return tensor.stride(0)
    raise RuntimeError(f"LSTM bias tensors must be 1-D, got {tensor.dim()}-D")


def _param_group(params, index: int, has_biases: bool):
    group_size = 4 if has_biases else 2
    base = index * group_size
    if has_biases:
        return params[base], params[base + 1], params[base + 2], params[base + 3]
    return params[base], params[base + 1], params[base], params[base]


def _copy_hx_slice(src, dst, state_idx: int, batch_size: int, hidden_size: int):
    if dst.numel() == 0:
        return
    grid = (triton.cdiv(dst.numel(), _COPY_BLOCK),)
    with torch_device_fn.device(dst.device):
        _copy_hx_slice_kernel[grid](
            src,
            dst,
            state_idx,
            batch_size,
            hidden_size,
            src.stride(0),
            src.stride(1),
            src.stride(2),
            BLOCK=_COPY_BLOCK,
        )


def _store_hx_slice(src, dst, state_idx: int, batch_size: int, hidden_size: int):
    if src.numel() == 0:
        return
    grid = (triton.cdiv(src.numel(), _COPY_BLOCK),)
    with torch_device_fn.device(src.device):
        _store_hx_slice_kernel[grid](
            src,
            dst,
            state_idx,
            batch_size,
            hidden_size,
            dst.stride(0),
            dst.stride(1),
            dst.stride(2),
            BLOCK=_COPY_BLOCK,
        )


def _run_direction(
    layer_input,
    hx,
    cx,
    layer_output,
    final_h,
    final_c,
    params,
    state_idx: int,
    param_idx: int,
    out_feature_offset: int,
    input_size: int,
    hidden_size: int,
    batch_size: int,
    seq_len: int,
    has_biases: bool,
    reverse: bool,
):
    w_ih, w_hh, b_ih, b_hh = _param_group(params, param_idx, has_biases)
    w_ih_stride_r, w_ih_stride_c = _matrix_strides(w_ih, 4 * hidden_size, input_size)
    w_hh_stride_r, w_hh_stride_c = _matrix_strides(w_hh, 4 * hidden_size, hidden_size)
    b_ih_stride = _bias_stride(b_ih, 4 * hidden_size) if has_biases else 1
    b_hh_stride = _bias_stride(b_hh, 4 * hidden_size) if has_biases else 1

    h_work = torch.empty((batch_size, hidden_size), device=hx.device, dtype=hx.dtype)
    c_work = torch.empty((batch_size, hidden_size), device=cx.device, dtype=cx.dtype)
    h_next = torch.empty_like(h_work)
    c_next = torch.empty_like(c_work)
    _copy_hx_slice(hx, h_work, state_idx, batch_size, hidden_size)
    _copy_hx_slice(cx, c_work, state_idx, batch_size, hidden_size)
    if batch_size == 0:
        return

    block_h = _block_size(hidden_size, _BLOCK_H_MAX)
    block_k = _block_size(max(input_size, hidden_size), _BLOCK_K_MAX)
    grid = (
        triton.cdiv(batch_size, _BLOCK_B),
        triton.cdiv(hidden_size, block_h),
    )
    with torch_device_fn.device(layer_input.device):
        for step in range(seq_len):
            seq_idx = seq_len - 1 - step if reverse else step
            _lstm_step_kernel[grid](
                layer_input,
                h_work,
                c_work,
                w_ih,
                w_hh,
                b_ih,
                b_hh,
                h_next,
                c_next,
                layer_output,
                seq_idx,
                out_feature_offset,
                input_size,
                hidden_size,
                batch_size,
                layer_input.stride(0),
                layer_input.stride(1),
                layer_input.stride(2),
                w_ih_stride_r,
                w_ih_stride_c,
                w_hh_stride_r,
                w_hh_stride_c,
                b_ih_stride,
                b_hh_stride,
                layer_output.stride(0),
                layer_output.stride(1),
                layer_output.stride(2),
                HAS_BIAS=has_biases,
                BLOCK_B=_BLOCK_B,
                BLOCK_H=block_h,
                BLOCK_K=block_k,
            )
            h_work, h_next = h_next, h_work
            c_work, c_next = c_next, c_work

    _store_hx_slice(h_work, final_h, state_idx, batch_size, hidden_size)
    _store_hx_slice(c_work, final_c, state_idx, batch_size, hidden_size)


def _validate_args(input, hx, params, has_biases, num_layers, dropout, bidirectional):
    if input.dim() != 3:
        raise RuntimeError("lstm: input must have 3 dimensions")
    if not isinstance(hx, (tuple, list)) or len(hx) != 2:
        raise RuntimeError("lstm expects two hidden states")
    if num_layers <= 0:
        raise RuntimeError("lstm: num_layers must be greater than zero")
    if not 0.0 <= dropout <= 1.0:
        raise RuntimeError("lstm: dropout probability must be between 0 and 1")
    if input.dtype not in (torch.float16, torch.bfloat16, torch.float32):
        raise NotImplementedError(
            "FlagGems lstm supports float16, bfloat16, and float32"
        )

    hx0, cx0 = hx
    if hx0.shape != cx0.shape:
        raise RuntimeError("lstm: hidden and cell states must have the same shape")
    if hx0.dim() != 3:
        raise RuntimeError("lstm: hidden and cell states must have 3 dimensions")
    num_directions = 2 if bidirectional else 1
    expected_states = num_layers * num_directions
    if hx0.shape[0] != expected_states:
        raise RuntimeError(
            f"lstm: expected {expected_states} hidden state rows, got {hx0.shape[0]}"
        )
    expected_params = expected_states * (4 if has_biases else 2)
    if len(params) != expected_params:
        raise RuntimeError(
            f"lstm: expected {expected_params} parameter tensors, got {len(params)}"
        )
    if hx0.device != input.device or cx0.device != input.device:
        raise RuntimeError(
            "lstm: input, hidden state, and cell state must share a device"
        )
    if hx0.dtype != input.dtype or cx0.dtype != input.dtype:
        raise RuntimeError(
            "lstm: input, hidden state, and cell state must share a dtype"
        )


def lstm(
    input,
    hx,
    params,
    has_biases=True,
    num_layers=1,
    dropout=0.0,
    train=False,
    bidirectional=False,
    batch_first=False,
):
    logger.debug("GEMS LSTM")
    _validate_args(input, hx, params, has_biases, num_layers, dropout, bidirectional)

    if batch_first:
        batch_size, seq_len, input_size = input.shape
        input_view = input.transpose(0, 1)
    else:
        seq_len, batch_size, input_size = input.shape
        input_view = input
    if seq_len == 0:
        raise RuntimeError("Expected sequence length to be larger than 0 in RNN")

    hx0, cx0 = hx
    hidden_size = hx0.shape[2]
    num_directions = 2 if bidirectional else 1
    final_h = torch.empty(
        (num_layers * num_directions, batch_size, hidden_size),
        device=input.device,
        dtype=input.dtype,
    )
    final_c = torch.empty_like(final_h)

    layer_input = input_view
    for layer in range(num_layers):
        layer_input_size = input_size if layer == 0 else hidden_size * num_directions
        layer_output = torch.empty(
            (seq_len, batch_size, hidden_size * num_directions),
            device=input.device,
            dtype=input.dtype,
        )
        for direction in range(num_directions):
            state_idx = layer * num_directions + direction
            reverse = direction == 1
            _run_direction(
                layer_input,
                hx0,
                cx0,
                layer_output,
                final_h,
                final_c,
                params,
                state_idx,
                state_idx,
                direction * hidden_size,
                layer_input_size,
                hidden_size,
                batch_size,
                seq_len,
                has_biases,
                reverse,
            )

        layer_input = layer_output
        if train and dropout != 0.0 and layer + 1 < num_layers:
            layer_input, _ = _dropout(layer_input, dropout, True)

    output = layer_input.transpose(0, 1) if batch_first else layer_input
    return output, final_h, final_c
