# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 128}, num_warps=4, num_stages=1),
        triton.Config({"BLOCK_SIZE": 256}, num_warps=4, num_stages=1),
        triton.Config({"BLOCK_SIZE": 512}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8, num_stages=1),
    ],
    key=["numel"],
)
@triton.jit
def max_unpool3d_kernel(
    input_ptr,
    indices_ptr,
    output_ptr,
    # Input strides
    in_stride_n,
    in_stride_c,
    # Output strides
    out_stride_n,
    out_stride_c,
    out_stride_d,
    out_stride_h,
    out_stride_w,
    # Shapes
    in_n,
    in_c,
    in_d,
    in_h,
    in_w,
    out_d,
    out_h,
    out_w,
    numel: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """
    max_unpool3d: scatter values from input to output based on indices.
    - input: pooled tensor of shape (N, C, in_d, in_h, in_w)
    - indices: tensor of same shape as input, containing linear indices in output space
    - output: unpooled tensor of shape (N, C, out_d, out_h, out_w)
    """
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < numel

    # Calculate n, c indices for this batch
    nc_idx = offsets // (in_d * in_h * in_w)
    in_offset = offsets % (in_d * in_h * in_w)

    n_idx = nc_idx // in_c
    c_idx = nc_idx % in_c

    # Compute input data pointer offsets
    input_base = n_idx * in_stride_n + c_idx * in_stride_c
    indices_base = n_idx * in_stride_n + c_idx * in_stride_c

    # Load values from input at each position
    vals = tl.load(input_ptr + input_base + in_offset, mask=mask, other=0.0)

    # Load indices (these are linear indices in output space)
    idxs = tl.load(indices_ptr + indices_base + in_offset, mask=mask, other=-1)

    # Calculate output coordinates from indices
    # idx = d * (out_h * out_w) + h * out_w + w
    d_out = idxs // (out_h * out_w)
    remainder = idxs % (out_h * out_w)
    h_out = remainder // out_w
    w_out = remainder % out_w

    # Check bounds
    valid = (
        (d_out >= 0)
        & (d_out < out_d)
        & (h_out >= 0)
        & (h_out < out_h)
        & (w_out >= 0)
        & (w_out < out_w)
        & (idxs >= 0)
    )

    # Compute output pointer offsets
    out_base = n_idx * out_stride_n + c_idx * out_stride_c
    out_offsets = (
        out_base + d_out * out_stride_d + h_out * out_stride_h + w_out * out_stride_w
    )

    # Store values to output - use atomic max for correctness with potential collisions
    # Actually, since this is max unpool, we should use atomic max
    # But we need to handle the case where multiple threads might write to the same location
    # For now, we'll do a simple store (works when indices are unique per channel)
    tl.store(output_ptr + out_offsets, vals, mask=mask & valid)


def max_unpool3d(
    input: torch.Tensor,
    indices: torch.Tensor,
    kernel_size,
    stride=None,
    padding=0,
    output_size=None,
):
    logger.debug("GEMS MAX_UNPOOL3D")
    input = input.contiguous()
    indices = indices.contiguous()

    # Parse parameters
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size,) * 3
    if stride is None:
        stride = kernel_size
    elif isinstance(stride, int):
        stride = (stride,) * 3
    if isinstance(padding, int):
        padding = (padding,) * 3

    in_n, in_c, in_d, in_h, in_w = input.shape

    # Compute output size
    if output_size is None:
        out_d = (in_d - 1) * stride[0] - 2 * padding[0] + kernel_size[0]
        out_h = (in_h - 1) * stride[1] - 2 * padding[1] + kernel_size[1]
        out_w = (in_w - 1) * stride[2] - 2 * padding[2] + kernel_size[2]
        output_size = (out_d, out_h, out_w)

    out_d, out_h, out_w = output_size

    # Allocate output
    output = torch.zeros(
        (in_n, in_c, out_d, out_h, out_w), device=input.device, dtype=input.dtype
    )

    if output.numel() == 0:
        return output

    numel = in_n * in_c * in_d * in_h * in_w

    grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)

    max_unpool3d_kernel[grid](
        input,
        indices,
        output,
        # Input strides
        input.stride(0),
        input.stride(1),
        # Output strides
        output.stride(0),
        output.stride(1),
        output.stride(2),
        output.stride(3),
        output.stride(4),
        # Shapes
        in_n,
        in_c,
        in_d,
        in_h,
        in_w,
        out_d,
        out_h,
        out_w,
        numel,
    )

    return output
