# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
from torch import Tensor

from flag_gems.ops.batch_norm import batch_norm_backward_kernel, make_3d_for_bn
from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


def miopen_batch_norm_backward(
    input: Tensor,
    grad_output: Tensor,
    weight: Tensor,
    running_mean: Tensor,
    running_var: Tensor,
    save_mean: Tensor,
    save_var: Tensor,
    epsilon: float,
) -> tuple:
    """Backward pass for batch normalization (MIOpen variant).

    This is a wrapper around the native batch_norm_backward. The MIOpen schema
    calls the saved inverse standard deviation argument save_var.

    Args:
        input: The input tensor.
        grad_output: Gradient of the loss w.r.t. the output.
        weight: The weight tensor.
        running_mean: The running mean.
        running_var: The running variance.
        save_mean: Saved mean from the forward pass.
        save_var: Saved inverse standard deviation from the forward pass.
        epsilon: Small constant for numerical stability.

    Returns:
        Tuple of (grad_input, grad_weight, grad_bias).
    """
    logger.debug("GEMS MIOPEN_BATCH_NORM_BACKWARD")

    save_invstd = save_var

    input_3d = make_3d_for_bn(input)
    grad_output_3d = make_3d_for_bn(grad_output)

    batch_dim, feat_dim, spatial_dim = input_3d.shape

    # Always compute all 3 gradients (no output_mask)
    input_grad = torch.empty_like(input_3d)
    weight_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
    bias_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)

    # Launches 1D grid where each program operates over one feature.
    with torch_device_fn.device(input.device):
        batch_norm_backward_kernel[(feat_dim,)](
            grad_output_3d,
            input_3d,
            save_mean,
            save_invstd,
            weight,
            input_grad,
            weight_grad,
            bias_grad,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            *input_grad.stride(),
            # output_mask: all True to compute all gradients
            True,  # input_grad_mask
            True,  # weight_grad_mask
            True,  # bias_grad_mask
        )

    # Return all 3 gradients
    return (
        input_grad.view_as(input),
        weight_grad,
        bias_grad,
    )
