# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)

_tanh = tl_extra_shim.tanh


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def mish_func(x):
    # mish(x) = x * tanh(softplus(x)) = x * tanh(ln(1 + e^x))
    x_fp32 = x.to(tl.float32)
    return (x_fp32 * _tanh(tl.log(1 + tl.exp(x_fp32)))).to(x.dtype)


def mish(A):
    logger.debug("GEMS MISH")
    return mish_func(A)


def mish_(A):
    logger.debug("GEMS MISH_")
    return mish_func(A, out0=A)
