# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)


@triton.jit
def _fallback_lgamma(x):
    z = x - 1.0
    a = 0.9999999999998099
    a += 676.5203681218851 / (z + 1.0)
    a += -1259.1392167224028 / (z + 2.0)
    a += 771.3234287776531 / (z + 3.0)
    a += -176.6150291621406 / (z + 4.0)
    a += 12.507343278686905 / (z + 5.0)
    a += -0.13857109526572012 / (z + 6.0)
    a += 9.984369578019572e-6 / (z + 7.0)
    a += 1.5056327351493116e-7 / (z + 8.0)
    t = z + 7.5
    return 0.9189385332046727 + (z + 0.5) * tl.log(t) - t + tl.log(a)


_lgamma = getattr(tl_extra_shim, "lgamma", _fallback_lgamma)


@triton.jit
def mvlgamma_kernel_(
    x_ptr,
    n_elements,
    p_val,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    x_f32 = x.to(tl.float32)

    # Load p value
    p = tl.load(p_val)

    # Compute the constant term: p * (p - 1) / 4 * log(π)
    LOG_PI = 1.1447298858494002  # log(π)
    LOG_PI_OVER_4 = LOG_PI / 4.0

    p_f32 = p.to(tl.float32)
    constant_term = p_f32 * (p_f32 - 1.0) * LOG_PI_OVER_4

    # Compute sum of lgamma terms: sum_{k=0}^{p-1} lgamma(x - k/2)
    sum_term = tl.zeros_like(x_f32)

    # Unrolled loop for common p values (1 to 12)
    t0 = _lgamma(x_f32 - 0.0)
    t1 = _lgamma(x_f32 - 0.5)
    t2 = _lgamma(x_f32 - 1.0)
    t3 = _lgamma(x_f32 - 1.5)
    t4 = _lgamma(x_f32 - 2.0)
    t5 = _lgamma(x_f32 - 2.5)
    t6 = _lgamma(x_f32 - 3.0)
    t7 = _lgamma(x_f32 - 3.5)
    t8 = _lgamma(x_f32 - 4.0)
    t9 = _lgamma(x_f32 - 4.5)
    t10 = _lgamma(x_f32 - 5.0)
    t11 = _lgamma(x_f32 - 5.5)

    # Select based on p at runtime using tl.where
    sum_term = t0
    sum_term = tl.where(p >= 2, sum_term + t1, sum_term)
    sum_term = tl.where(p >= 3, sum_term + t2, sum_term)
    sum_term = tl.where(p >= 4, sum_term + t3, sum_term)
    sum_term = tl.where(p >= 5, sum_term + t4, sum_term)
    sum_term = tl.where(p >= 6, sum_term + t5, sum_term)
    sum_term = tl.where(p >= 7, sum_term + t6, sum_term)
    sum_term = tl.where(p >= 8, sum_term + t7, sum_term)
    sum_term = tl.where(p >= 9, sum_term + t8, sum_term)
    sum_term = tl.where(p >= 10, sum_term + t9, sum_term)
    sum_term = tl.where(p >= 11, sum_term + t10, sum_term)
    sum_term = tl.where(p >= 12, sum_term + t11, sum_term)

    result = constant_term + sum_term
    result = result.to(x.dtype)
    tl.store(x_ptr + offsets, result, mask=mask)


def mvlgamma_(*args, **kwargs):
    logger.debug("GEMS MVLGAMMA_")
    x = args[0]
    p = args[1] if len(args) > 1 else kwargs.get("p", 1)

    if not isinstance(x, torch.Tensor):
        raise TypeError("mvlgamma_ expects a torch.Tensor as the first argument")

    if not isinstance(p, int) or p < 1:
        raise ValueError("p must be a positive integer")

    # Limit p to 12 since we unrolled the loop 12 times
    if p > 12:
        raise ValueError("p must be <= 12 for this implementation")

    # Create a 1D tensor to pass p to the kernel
    p_tensor = torch.tensor([p], dtype=torch.int32, device=x.device)

    # Handle non-contiguous tensors by operating on a contiguous copy and copying back
    if not x.is_contiguous():
        y = x.contiguous()
        n_elements = y.numel()
        if n_elements == 0:
            return x
        grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
        with torch_device_fn.device(y.device):
            mvlgamma_kernel_[grid](y, n_elements, p_tensor, BLOCK_SIZE=1024)
        x.copy_(y)
        return x

    n_elements = x.numel()
    if n_elements == 0:
        return x
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        mvlgamma_kernel_[grid](x, n_elements, p_tensor, BLOCK_SIZE=1024)
    return x
