# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def narrow_copy_kernel(
    out_ptr,
    inp_ptr,
    total_elements,
    inp_total_elements,
    dim_size,
    dim_prod_post,
    start,
    length,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = tl.arange(0, BLOCK_SIZE)
    mask = block_start + offsets < total_elements

    idx = block_start + offsets
    # Compute the flat index in the output tensor
    # Output dimensions: all dims same as input except the narrowed dim has size = length
    # We need to map from output flat index to input flat index
    pre_idx = idx // (length * dim_prod_post)
    dim_idx = (idx // dim_prod_post) % length
    post_idx = idx % dim_prod_post

    # Map to input tensor
    inp_dim_idx = dim_idx + start
    inp_idx = (
        pre_idx * dim_size * dim_prod_post + inp_dim_idx * dim_prod_post + post_idx
    )

    # Load from input and store to output
    inp_data = tl.load(inp_ptr + inp_idx, mask=mask)
    tl.store(out_ptr + idx, inp_data, mask=mask)


def narrow_copy(inp, dim, start, length):
    logger.debug("GEMS NARROW_COPY")
    assert (
        dim >= -inp.ndim and dim < inp.ndim
    ), f"Invalid dim: {dim} for tensor with {inp.ndim} dimensions"
    dim = dim % inp.ndim

    # Handle negative start
    if start < 0:
        start = start % inp.size(dim)

    # Clamp length to valid range
    length = min(length, inp.size(dim) - start)

    # Compute output shape
    out_shape = list(inp.shape)
    out_shape[dim] = length
    out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)

    if out.numel() == 0:
        return out

    total_elements = out.numel()
    dim_size = inp.size(dim)
    inp_total_elements = inp.numel()

    # Compute the product of dimensions after the narrowed dim
    dim_prod_post = 1
    for d in range(dim + 1, inp.ndim):
        dim_prod_post *= inp.size(d)

    # Use 1024 as default block size; balances occupancy and memory bandwidth for copy kernel
    BLOCK_SIZE = 1024
    grid = (triton.cdiv(total_elements, BLOCK_SIZE),)

    # Make input contiguous for simpler indexing
    inp = inp.contiguous()

    narrow_copy_kernel[grid](
        out,
        inp,
        total_elements,
        inp_total_elements,
        dim_size,
        dim_prod_post,
        start,
        length,
        BLOCK_SIZE=BLOCK_SIZE,
    )

    return out
