# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def rad2deg_func(x):
    # 180.0 / pi
    return (x.to(tl.float32) * 57.29577951308232).to(x.dtype)


def rad2deg(A):
    logger.debug("GEMS RAD2DEG")
    return rad2deg_func(A)


def rad2deg_(A):
    logger.debug("GEMS RAD2DEG_")
    rad2deg_func(A, out0=A)
    return A
