# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def reflection_pad1d_backward_kernel(
    grad_output_ptr,
    grad_input_ptr,
    B,
    W_in,
    pad_left,
    W_out,
    BLOCK_W: tl.constexpr,
):
    pid_b = tl.program_id(axis=0)
    pid_w = tl.program_id(axis=1)

    offs_w = pid_w * BLOCK_W + tl.arange(0, BLOCK_W)
    mask = offs_w < W_in

    base_out = pid_b * W_out
    base_in = pid_b * W_in

    # Each input element receives the center gradient and, when reflected,
    # at most one contribution from each padded side.
    center_out = pad_left + offs_w
    acc = tl.load(grad_output_ptr + base_out + center_out, mask=mask, other=0.0).to(
        tl.float32
    )

    left_mask = mask & (offs_w > 0) & (offs_w <= pad_left)
    left_out = tl.where(left_mask, pad_left - offs_w, 0)
    acc += tl.load(grad_output_ptr + base_out + left_out, mask=left_mask, other=0.0).to(
        tl.float32
    )

    pad_right = W_out - W_in - pad_left
    right_start = W_in - pad_right - 1
    right_mask = mask & (offs_w < W_in - 1) & (offs_w >= right_start)
    right_out = tl.where(right_mask, pad_left + 2 * (W_in - 1) - offs_w, 0)
    acc += tl.load(
        grad_output_ptr + base_out + right_out, mask=right_mask, other=0.0
    ).to(tl.float32)

    tl.store(grad_input_ptr + base_in + offs_w, acc, mask=mask)


def _launch_reflection_pad1d_backward(
    grad_output: torch.Tensor,
    input: torch.Tensor,
    padding,
):
    if not isinstance(padding, (list, tuple)) or len(padding) != 2:
        raise ValueError(
            "padding must be a sequence of length 2: (pad_left, pad_right)"
        )
    pad_left, pad_right = int(padding[0]), int(padding[1])
    if pad_left < 0 or pad_right < 0:
        raise ValueError("padding values must be >= 0")
    if input.dim() < 1:
        raise ValueError("input must have at least 1 dimension")

    grad_output = grad_output.contiguous()
    x = input.contiguous()

    W_in = int(x.shape[-1])
    if W_in <= 0:
        raise ValueError("last dimension (width) must be > 0")

    W_out = W_in + pad_left + pad_right
    leading_shape = x.shape[:-1]
    B = int(math.prod(leading_shape)) if len(leading_shape) > 0 else 1

    # No padding case - just copy
    if pad_left == 0 and pad_right == 0:
        if W_out != W_in:
            raise RuntimeError(
                "Internal error: W_out should equal W_in when no padding"
            )
        grad_input = torch.empty_like(x)
        grid = (B, triton.cdiv(W_in, 256))
        with torch_device_fn.device(x.device):
            _copy_rows_kernel[grid](grad_output, grad_input, B, W_in, BLOCK_W=256)
        return grad_input

    # Validate input dimensions
    if W_in < 2:
        raise ValueError(
            "input width must be at least 2 for reflection padding when padding > 0"
        )
    if pad_left >= W_in or pad_right >= W_in:
        raise ValueError(
            "padding values must be less than the input width for reflection padding"
        )

    grad_input = torch.empty_like(x)
    grid = (B, triton.cdiv(W_in, 256))
    with torch_device_fn.device(x.device):
        reflection_pad1d_backward_kernel[grid](
            grad_output, grad_input, B, W_in, pad_left, W_out, BLOCK_W=256
        )
    return grad_input


@triton.jit
def _copy_rows_kernel(in_ptr, out_ptr, B, W, BLOCK_W: tl.constexpr):
    pid_b = tl.program_id(axis=0)
    pid_w = tl.program_id(axis=1)

    offs_w = pid_w * BLOCK_W + tl.arange(0, BLOCK_W)
    mask = (offs_w < W) & (pid_b < B)

    base = pid_b * W
    vals = tl.load(in_ptr + base + offs_w, mask=mask, other=0)
    tl.store(out_ptr + base + offs_w, vals, mask=mask)


def reflection_pad1d_backward(grad_output: torch.Tensor, input: torch.Tensor, padding):
    logger.debug("GEMS REFLECTION_PAD1D_BACKWARD")
    return _launch_reflection_pad1d_backward(grad_output, input, padding)
