# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import Optional

import torch
import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def _resize_as_kernel(src):
    return src


def resize_as(
    self: torch.Tensor,
    the_template: torch.Tensor,
    *,
    memory_format: Optional[torch.memory_format] = None,
):
    logger.debug("GEMS RESIZE_AS")

    if memory_format is None:
        memory_format = torch.contiguous_format

    # Check if already same shape
    if self.shape == the_template.shape:
        return self

    # Validate element count (PyTorch requires same number of elements for autograd)
    if self.numel() != the_template.numel():
        raise RuntimeError(
            f"requested resize to {tuple(the_template.shape)} ({the_template.numel()} elements in total), "
            f"but the given tensor has a size of {tuple(self.shape)} ({self.numel()} elements in total). "
            f"autograd's resize can only change the shape of a given tensor, while preserving the number of elements."
        )

    # Create output tensor with target shape
    out = torch.empty(the_template.size(), device=self.device, dtype=self.dtype)

    # Reshape source to destination shape (numel already verified equal).
    src = self.reshape(the_template.shape)

    # Handle empty tensors
    if self.numel() == 0:
        return out

    overload = _resize_as_kernel.instantiate(src.ndim)
    overload(src, out0=out)
    return out


def resize_as_(
    self: torch.Tensor,
    the_template: torch.Tensor,
    *,
    memory_format: Optional[torch.memory_format] = None,
):
    logger.debug("GEMS RESIZE_AS_")

    if memory_format is None:
        memory_format = torch.contiguous_format

    # Check if already same shape
    if self.shape == the_template.shape:
        return self

    # Validate element count
    if self.numel() != the_template.numel():
        raise RuntimeError(
            f"requested resize to {tuple(the_template.shape)} ({the_template.numel()} elements in total), "
            f"but the given tensor has a size of {tuple(self.shape)} ({self.numel()} elements in total). "
            f"autograd's resize can only change the shape of a given tensor, while preserving the number of elements."
        )

    # Resize in-place: change self to match template shape
    self.resize_(the_template.size())

    # If shapes differ, we need to copy data (but since it's in-place resize,
    # the data is already there, just reinterpreted)
    return self
