# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def sgn_real_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
    IS_BOOL: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)

    if IS_BOOL:
        result = x
    else:
        pos = x > 0
        neg = x < 0
        result = pos.to(x.dtype) - neg.to(x.dtype)

    tl.store(out_ptr + offsets, result, mask=mask)


@triton.jit
def sgn_complex_kernel(
    x_ri_ptr,
    out_ri_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
    COMPUTE_IN_FP32: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    base = offsets * 2
    real = tl.load(x_ri_ptr + base, mask=mask, other=0.0)
    imag = tl.load(x_ri_ptr + base + 1, mask=mask, other=0.0)

    if COMPUTE_IN_FP32:
        real_compute = real.to(tl.float32)
        imag_compute = imag.to(tl.float32)
    else:
        real_compute = real
        imag_compute = imag

    abs_real = tl.abs(real_compute)
    abs_imag = tl.abs(imag_compute)
    scale = tl.maximum(abs_real, abs_imag)
    is_zero = scale == 0.0
    safe_scale = tl.where(is_zero, 1.0, scale)

    # Overflow-safe magnitude for finite inputs (mirrors std::hypot scaling).
    scaled_real = real_compute / safe_scale
    scaled_imag = imag_compute / safe_scale
    finite_norm = scale * tl.sqrt(scaled_real * scaled_real + scaled_imag * scaled_imag)

    # Match torch.sgn's complex abs (std::hypot): an infinite component makes the
    # magnitude inf (dominating any NaN); otherwise a NaN propagates. Dividing the
    # original components by this magnitude then reproduces IEEE semantics per
    # component, e.g. (inf + 1j) -> (nan, 0) and (1 + infj) -> (0, nan).
    has_inf = (abs_real == float("inf")) | (abs_imag == float("inf"))
    has_nan = (real_compute != real_compute) | (imag_compute != imag_compute)
    norm = tl.where(has_inf, float("inf"), tl.where(has_nan, float("nan"), finite_norm))
    safe_norm = tl.where(is_zero, 1.0, norm)

    out_real = tl.where(is_zero, 0.0, real_compute / safe_norm)
    out_imag = tl.where(is_zero, 0.0, imag_compute / safe_norm)

    tl.store(out_ri_ptr + base, out_real, mask=mask)
    tl.store(out_ri_ptr + base + 1, out_imag, mask=mask)


def _sgn_impl(x: torch.Tensor, out: torch.Tensor):
    if x.device != out.device:
        raise RuntimeError("input and out must be on the same device")
    if x.dtype != out.dtype:
        raise RuntimeError(f"out must have dtype {x.dtype}, but got {out.dtype}")
    if out.shape != x.shape:
        out.resize_(x.shape)

    n_elements = x.numel()
    if n_elements == 0:
        return out

    x_contig = x.contiguous()
    if out.is_contiguous():
        out_contig = out
    else:
        out_contig = torch.empty_like(x, memory_format=torch.contiguous_format)

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        if x.is_complex():
            x_ri = torch.view_as_real(x_contig).view(-1)
            out_ri = torch.view_as_real(out_contig).view(-1)
            sgn_complex_kernel[grid](
                x_ri,
                out_ri,
                n_elements,
                BLOCK_SIZE=1024,
                COMPUTE_IN_FP32=x.dtype in (torch.complex32, torch.complex64),
            )
        else:
            sgn_real_kernel[grid](
                x_contig.view(-1),
                out_contig.view(-1),
                n_elements,
                BLOCK_SIZE=1024,
                IS_BOOL=x.dtype == torch.bool,
            )

    if out_contig is not out:
        out.copy_(out_contig)
    return out


def sgn(x: torch.Tensor):
    logger.debug("GEMS SGN")
    out = torch.empty_like(x)
    return _sgn_impl(x, out)


def sgn_out(x: torch.Tensor, *, out: torch.Tensor):
    logger.debug("GEMS SGN_OUT")
    return _sgn_impl(x, out)
