# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

import flag_gems
from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def special_scaled_modified_bessel_k1_kernel(
    x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # Handle non-positive values
    zero = 0.0
    ax = tl.abs(x_f32)
    is_zero = ax < 1e-30
    is_negative = x_f32 < zero

    # ================================================================
    # Small region: 0 < x <= 2.0
    # scaled_K1(x) = exp(x) * K1(x)
    # K1(x) = log(x/2) * I1(x) + P(x) / x
    # P(x) evaluated via Chebyshev series in w = x - 1 (degree 10, 11 terms).
    # ================================================================

    # --- Step 1: Compute I1(x) via Cephes polynomial (valid for x <= 3.75) ---
    y_i1 = x_f32 / 3.75
    y2_i1 = y_i1 * y_i1
    p_i1 = 0.00032411
    p_i1 = 0.00301532 + y2_i1 * p_i1
    p_i1 = 0.02658733 + y2_i1 * p_i1
    p_i1 = 0.15084934 + y2_i1 * p_i1
    p_i1 = 0.51498869 + y2_i1 * p_i1
    p_i1 = 0.87890594 + y2_i1 * p_i1
    p_i1 = 0.5 + y2_i1 * p_i1
    i1_val = x_f32 * p_i1

    # --- Step 2: Chebyshev series for P(x) at w = x - 1 ---
    # Clenshaw recurrence (3-state, correct update order):
    #   b_2 = b_1; b_1 = b_0; b_0 = c_k + 2*y*b_1 - b_2
    # Result: (b_0 - b_2) / 2
    y_cheb = x_f32 - 1.0
    b0 = 0.0
    b1 = 0.0

    # k=10: T_10 coefficient
    b2 = b1
    b1 = b0
    b0 = -3.662620162661560e-09 + 2.0 * y_cheb * b1 - b2

    # k=9: T_9 coefficient
    b2 = b1
    b1 = b0
    b0 = -5.350617072358099e-08 + 2.0 * y_cheb * b1 - b2

    # k=8: T_8 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.045185163440483e-06 + 2.0 * y_cheb * b1 - b2

    # k=7: T_7 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.201112421320492e-05 + 2.0 * y_cheb * b1 - b2

    # k=6: T_6 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.699042469646379e-04 + 2.0 * y_cheb * b1 - b2

    # k=5: T_5 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.426485944971723e-03 + 2.0 * y_cheb * b1 - b2

    # k=4: T_4 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.225928401715418e-02 + 2.0 * y_cheb * b1 - b2

    # k=3: T_3 coefficient
    b2 = b1
    b1 = b0
    b0 = -6.428271235627786e-02 + 2.0 * y_cheb * b1 - b2

    # k=2: T_2 coefficient
    b2 = b1
    b1 = b0
    b0 = -1.767199860308625e-01 + 2.0 * y_cheb * b1 - b2

    # k=1: T_1 coefficient
    b2 = b1
    b1 = b0
    b0 = -2.944128552518444e-01 + 2.0 * y_cheb * b1 - b2

    # k=0: T_0 coefficient (doubled for Clenshaw halving convention)
    b2 = b1
    b1 = b0
    b0 = 1.658032209918573e00 + 2.0 * y_cheb * b1 - b2

    # Final Chebyshev value: (b_0 - b_2) / 2
    cheb_val = (b0 - b2) / 2.0

    # --- Step 3: Compute K1(x) and scaled_K1(x) ---
    # K1(x) = log(x/2) * I1(x) + cheb_val / x
    # scaled_K1(x) = exp(x) * K1(x)
    log_term = tl.log(tl.maximum(x_f32, 1e-30) / 2.0)
    k1_small = log_term * i1_val + cheb_val / tl.maximum(x_f32, 1e-30)
    small_result = tl.exp(x_f32) * k1_small

    # ================================================================
    # Mid region: 2.0 < x <= 8.0
    # Polynomial fit for sqrt(x) * scaled_K1(x) in t = 1/x
    # scaled_K1(x) = poly(1/x) / sqrt(x)
    # ================================================================
    t_mid = 1.0 / ax
    # Horner evaluation of degree-9 polynomial fitted on [2, 5]
    poly_mid = 1.787118672412693
    poly_mid = 8.623190654362435 + t_mid * poly_mid
    poly_mid = -31.24007105377005 + t_mid * poly_mid
    poly_mid = 39.94627099526494 + t_mid * poly_mid
    poly_mid = -27.61325465617906 + t_mid * poly_mid
    poly_mid = 11.54410129937854 + t_mid * poly_mid
    poly_mid = -2.958011161687468 + t_mid * poly_mid
    poly_mid = 0.352116615179864 + t_mid * poly_mid
    poly_mid = 0.424654857840721 + t_mid * poly_mid
    poly_mid = 1.255087565900909 + t_mid * poly_mid
    mid_result = poly_mid / tl.sqrt(ax)

    # ================================================================
    # Large region: x > 8.0
    # Use asymptotic expansion for scaled_K1 directly:
    #   scaled_K1(x) = sqrt(pi/(2x)) * sum_{k=0}^5 (1,k) / (2x)^k
    # where (1,k) are the Bessel asymptotic coefficients.
    # ================================================================
    t_large = 1.0 / ax
    # Horner polynomial: 1 + 3t/8 - 15t^2/128 + 105t^3/1024 - 4725t^4/32768 + 72765t^5/262144
    poly_large = 1.0 + t_large * (
        0.375  # 3/8
        + t_large
        * (
            -0.1171875  # -15/128
            + t_large
            * (
                0.1025390625  # 105/1024
                + t_large
                * (
                    -0.144195556640625  # -4725/32768
                    + t_large * 0.277576446533203125  # 72765/262144
                )
            )
        )
    )
    # sqrt(pi/2) = 1.2533141373155001
    big_result = 1.2533141373155001 * poly_large / tl.sqrt(ax)

    # Combine results: three regions
    use_small = ax <= 2.0
    use_mid = (ax > 2.0) & (ax <= 8.0)
    result = tl.where(
        use_small, small_result, tl.where(use_mid, mid_result, big_result)
    )

    # Handle singularity at x=0 -> infinity
    result = tl.where(is_zero, float("inf"), result)
    # Handle negative inputs: return nan (matching PyTorch behavior)
    result = tl.where(is_negative, float("nan"), result)

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_special_scaled_modified_bessel_k1(out: torch.Tensor, x: torch.Tensor):
    if x.device.type != flag_gems.device or out.device.type != flag_gems.device:
        raise ValueError(f"Tensors must be {flag_gems.device} tensors")
    assert (
        out.numel() == x.numel()
    ), "Input and output must have the same number of elements"
    assert out.device == x.device, "Input and output must be on the same device"

    x_in = x
    out_in = out

    # Ensure floating point compute
    if not x_in.is_floating_point():
        x_in = x_in.to(torch.get_default_dtype())

    # Cast input to match the desired output dtype if needed
    if x_in.dtype != out_in.dtype:
        x_in = x_in.to(out_in.dtype)

    x_contig = x_in.contiguous()
    out_was_noncontig = not out_in.is_contiguous()
    out_contig = out_in.contiguous() if out_was_noncontig else out_in

    n_elements = out_contig.numel()
    if n_elements == 0:
        return

    # Balance occupancy and register pressure for Bessel kernel
    BLOCK_SIZE = 256
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        special_scaled_modified_bessel_k1_kernel[grid](
            x_contig, out_contig, n_elements, BLOCK_SIZE=BLOCK_SIZE
        )

    if out_was_noncontig:
        out_in.copy_(out_contig)
    return out_in


def special_scaled_modified_bessel_k1(x: torch.Tensor):
    logger.debug("GEMS SPECIAL_SCALED_MODIFIED_BESSEL_K1")
    if x.device.type != flag_gems.device:
        raise ValueError(
            "special_scaled_modified_bessel_k1: input tensor must be on CUDA device"
        )
    # Result dtype follows PyTorch's floating type behavior
    out_dtype = x.dtype if x.is_floating_point() else torch.get_default_dtype()
    out = torch.empty_like(x.to(dtype=out_dtype), dtype=out_dtype, device=x.device)
    _launch_special_scaled_modified_bessel_k1(out, x)
    return out


def special_scaled_modified_bessel_k1_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS SPECIAL_SCALED_MODIFIED_BESSEL_K1_OUT")
    if x.device.type != flag_gems.device or out.device.type != flag_gems.device:
        raise ValueError(
            "special_scaled_modified_bessel_k1_out: input and output tensors must be on CUDA device"
        )
    if not out.is_floating_point():
        raise TypeError(
            "special_scaled_modified_bessel_k1_out: output tensor must be a floating point type"
        )
    if x.numel() != out.numel():
        raise ValueError(
            "special_scaled_modified_bessel_k1_out: input and output must have the same number of elements"
        )
    _launch_special_scaled_modified_bessel_k1(out, x)
    return out
