# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""
Implementation of Airy Ai function.
Uses Taylor series near zero, Chebyshev approximation for moderate negative x,
and asymptotic expansions for large |x|.
"""

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_airy_ai_func(x):
    xf = x.to(tl.float32)

    # === Region 1: |x| <= 4 - Taylor series ===
    # Ai(x) = c1*f(x^3) + c2*x*g(x^3)
    # where f(t) = sum f_k * t^k, g(t) = sum g_k * t^k
    # c1 = Ai(0), c2 = Ai'(0)
    C1 = 3.55028053887817219e-01
    C2 = -2.58819403792806824e-01

    t = xf * xf * xf  # x^3

    # Horner evaluation of f(t), 14 terms
    # f[13] to f[0]
    f_val = 3.258014000211276e-32
    f_val = f_val * t + 4.828376748313110e-29
    f_val = f_val * t + 6.083754702874519e-26
    f_val = f_val * t + 6.424444966235493e-23
    f_val = f_val * t + 5.589267120624878e-20
    f_val = f_val * t + 3.923665518678665e-17
    f_val = f_val * t + 2.165863366310623e-14
    f_val = f_val * t + 9.096626138504616e-12
    f_val = f_val * t + 2.783567598382413e-09
    f_val = f_val * t + 5.845491956603067e-07
    f_val = f_val * t + 7.716049382716048e-05
    f_val = f_val * t + 5.555555555555555e-03
    f_val = f_val * t + 1.666666666666667e-01
    f_val = f_val * t + 1.0

    # Horner evaluation of g(t), 14 terms
    g_val = 3.789181060402651e-33
    g_val = g_val * t + 5.911122454228137e-30
    g_val = g_val * t + 7.873615109031878e-27
    g_val = g_val * t + 8.834196152333768e-24
    g_val = g_val * t + 8.215802421670404e-21
    g_val = g_val * t + 6.211146630782826e-18
    g_val = g_val * t + 3.726687978469696e-15
    g_val = g_val * t + 1.721729846053000e-12
    g_val = g_val * t + 5.888316073501258e-10
    g_val = g_val * t + 1.413195857640302e-07
    g_val = g_val * t + 2.204585537918871e-05
    g_val = g_val * t + 1.984126984126984e-03
    g_val = g_val * t + 8.333333333333333e-02
    g_val = g_val * t + 1.0

    taylor_result = C1 * f_val + C2 * xf * g_val

    # === Region 2: -10 <= x < -4 - Chebyshev (Clenshaw), u=(x+7)/3 ===
    u2 = (xf + 7.0) / 3.0
    two_u2 = 2.0 * u2

    # Clenshaw recurrence for 18 Chebyshev coefficients
    # b_{k} = c_k + 2*u*b_{k+1} - b_{k+2}, starting from k=N down to k=1
    b2_next = 0.0
    b2_curr = 0.0
    # k=18
    b2_prev = 8.440612239504525e-06 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=17
    b2_prev = -3.855888775027948e-06 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=16
    b2_prev = -9.610482680254452e-05 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=15
    b2_prev = 2.183375580517599e-04 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=14
    b2_prev = 6.277438701116354e-04 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=13
    b2_prev = -2.847878413210169e-03 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=12
    b2_prev = -1.206496129633353e-03 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=11
    b2_prev = 2.011058181698241e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=10
    b2_prev = -1.256845149118993e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=9
    b2_prev = -7.898768427899136e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=8
    b2_prev = 9.150265355435239e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=7
    b2_prev = 1.516998426668974e-01 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=6
    b2_prev = -1.769682609630353e-01 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=5
    b2_prev = -8.897982884210892e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=4
    b2_prev = -7.455794938533478e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=3
    b2_prev = -5.567168539075128e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=2
    b2_prev = 8.925468398050689e-02 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # k=1
    b2_prev = -7.879477345484935e-04 + two_u2 * b2_curr - b2_next
    b2_next = b2_curr
    b2_curr = b2_prev
    # Final: result = c[0] + u*b1 - b2
    cheb2_result = 6.899318014205727e-02 + u2 * b2_curr - b2_next

    # === Region 3: -20 <= x < -10 - Chebyshev (Clenshaw), u=(x+15)/5 ===
    u3 = (xf + 15.0) / 5.0
    two_u3 = 2.0 * u3

    # Clenshaw recurrence for 30 Chebyshev coefficients
    b3_next = 0.0
    b3_curr = 0.0
    # k=30
    b3_prev = -7.116933440528689e-07 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=29
    b3_prev = -1.672444336509916e-04 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=28
    b3_prev = 1.655950742546957e-04 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=27
    b3_prev = 7.416322266157390e-04 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=26
    b3_prev = -1.499634912716068e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=25
    b3_prev = -2.450418779102568e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=24
    b3_prev = 8.273803587257341e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=23
    b3_prev = 4.093220089352211e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=22
    b3_prev = -3.088893188397790e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=21
    b3_prev = 3.973905002050232e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=20
    b3_prev = 7.739163324824742e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=19
    b3_prev = -3.916077185238313e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=18
    b3_prev = -1.192353429833762e-01 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=17
    b3_prev = 7.941589870203423e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=16
    b3_prev = 8.523557917738489e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=15
    b3_prev = -2.437616167043893e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=14
    b3_prev = 1.513727156712034e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=13
    b3_prev = -1.014130848193506e-01 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=12
    b3_prev = -4.205132524600607e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=11
    b3_prev = 1.659684202334219e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=10
    b3_prev = -2.177491307155626e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=9
    b3_prev = 1.075869141711292e-01 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=8
    b3_prev = 1.628444917285106e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=7
    b3_prev = 9.007855308353493e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=6
    b3_prev = -1.530340808228163e-03 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=5
    b3_prev = 3.005634628939965e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=4
    b3_prev = -2.243289742225448e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=3
    b3_prev = -1.730597966494768e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=2
    b3_prev = -3.294939040861621e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # k=1
    b3_prev = -3.945301260469057e-02 + two_u3 * b3_curr - b3_next
    b3_next = b3_curr
    b3_curr = b3_prev
    # Final
    cheb3_result = -1.779074863065543e-02 + u3 * b3_curr - b3_next

    # === Region 4: x > 4 - Positive asymptotic ===
    # Ai(x) ~ exp(-zeta) / (2*sqrt(pi)*x^(1/4)) * sum (-1)^k * u_k / zeta^k
    # zeta = 2/3 * x^(3/2)
    x_abs = tl.abs(xf)
    sqrt_x = tl.sqrt(x_abs)
    zeta = 0.6666666666666666 * x_abs * sqrt_x
    inv_zeta = 1.0 / zeta

    # 5-term asymptotic sum: 1 - u1/z + u2/z^2 - u3/z^3 + u4/z^4
    U1 = 6.944444444444444e-02
    U2 = 1.114004629629630e-01
    U3 = 5.698958869170097e-01
    U4 = 6.053164993330321e00

    asym_sum = 1.0 + inv_zeta * (
        -U1 + inv_zeta * (U2 + inv_zeta * (-U3 + inv_zeta * U4))
    )

    # Prefactor: exp(-zeta) / (2*sqrt(pi)*x^(1/4))
    RSQRT_PI_HALF = 0.28209479177387814  # 1/(2*sqrt(pi))
    x_quarter = tl.sqrt(sqrt_x)  # x^(1/4) via sqrt(sqrt(x))
    pos_asym_result = RSQRT_PI_HALF / x_quarter * tl.exp(-zeta) * asym_sum

    # === Region 5: x < -20 - Negative asymptotic ===
    # Ai(-t) ~ (1/(sqrt(pi)*t^(1/4))) * [sin(theta)*A + cos(theta)*B]
    # theta = zeta + pi/4 = 2/3*t^(3/2) + pi/4
    # A = 1 - u2/zeta^2 + u4/zeta^4
    # B = -u1/zeta + u3/zeta^3
    PI_QUARTER = 0.7853981633974483
    RSQRT_PI = 0.5641895835477563  # 1/sqrt(pi)

    theta = zeta + PI_QUARTER
    iz2 = inv_zeta * inv_zeta

    A_sum = 1.0 + iz2 * (-U2 + iz2 * U4)
    B_sum = inv_zeta * (-U1 + iz2 * U3)

    neg_amp = RSQRT_PI / x_quarter
    neg_asym_result = neg_amp * (tl.sin(theta) * A_sum + tl.cos(theta) * B_sum)

    # === Select result based on region ===
    # Default: taylor for |x| <= 4
    result = taylor_result
    # Override for x < -4 and x >= -10
    result = tl.where((xf < -4.0) & (xf >= -10.0), cheb2_result, result)
    # Override for x < -10 and x >= -20
    result = tl.where((xf < -10.0) & (xf >= -20.0), cheb3_result, result)
    # Override for x > 4 (positive asymptotic)
    result = tl.where(xf > 4.0, pos_asym_result, result)
    # Override for x < -20 (negative asymptotic)
    result = tl.where(xf < -20.0, neg_asym_result, result)

    return result.to(x.dtype)


def special_airy_ai(A):
    logger.debug("GEMS SPECIAL_AIRY_AI")
    return special_airy_ai_func(A)


def special_airy_ai_out(A, *, out=None):
    logger.debug("GEMS SPECIAL_AIRY_AI_OUT")
    if out is None:
        return special_airy_ai_func(A)
    special_airy_ai_func(A, out0=out)
    return out
