# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def shifted_chebyshev_polynomial_v_func(x, n):
    # Compute Chebyshev polynomial of the third kind V_n^*(x)
    # Shifted Chebyshev polynomial of the third kind on [0,1]:
    # V_0^*(x) = 1
    # V_1^*(x) = 4x - 3
    # V_n^*(x) = (4x-2) * V_{n-1}^* - V_{n-2}^*

    xf = x.to(tl.float32)
    nf = n.to(tl.int32)

    # Compute 4x - 2 (the coefficient in recurrence)
    four_x_minus_2 = 4.0 * xf - 2.0

    # V_0^*(x) = 1
    v0 = 1.0
    # V_1^*(x) = 4x - 3
    v1 = 4.0 * xf - 3.0
    # V_2^*(x) = (4x-2) * V_1^* - V_0^*
    v2 = four_x_minus_2 * v1 - v0
    # V_3^*(x)
    v3 = four_x_minus_2 * v2 - v1
    # V_4^*(x)
    v4 = four_x_minus_2 * v3 - v2
    # V_5^*(x)
    v5 = four_x_minus_2 * v4 - v3
    # V_6^*(x)
    v6 = four_x_minus_2 * v5 - v4
    # V_7^*(x)
    v7 = four_x_minus_2 * v6 - v5
    # V_8^*(x)
    v8 = four_x_minus_2 * v7 - v6
    # V_9^*(x)
    v9 = four_x_minus_2 * v8 - v7
    # V_10^*(x)
    v10 = four_x_minus_2 * v9 - v8
    # V_11^*(x)
    v11 = four_x_minus_2 * v10 - v9
    # V_12^*(x)
    v12 = four_x_minus_2 * v11 - v10
    # V_13^*(x)
    v13 = four_x_minus_2 * v12 - v11
    # V_14^*(x)
    v14 = four_x_minus_2 * v13 - v12
    # V_15^*(x)
    v15 = four_x_minus_2 * v14 - v13

    # Select the correct result based on n using arithmetic masking.
    # Arithmetic selection (multiply by bool mask) avoids the tl.where chain
    # issue where out-of-range n values receive indeterminate results.
    result = (
        (nf == 0).to(tl.float32) * v0
        + (nf == 1).to(tl.float32) * v1
        + (nf == 2).to(tl.float32) * v2
        + (nf == 3).to(tl.float32) * v3
        + (nf == 4).to(tl.float32) * v4
        + (nf == 5).to(tl.float32) * v5
        + (nf == 6).to(tl.float32) * v6
        + (nf == 7).to(tl.float32) * v7
        + (nf == 8).to(tl.float32) * v8
        + (nf == 9).to(tl.float32) * v9
        + (nf == 10).to(tl.float32) * v10
        + (nf == 11).to(tl.float32) * v11
        + (nf == 12).to(tl.float32) * v12
        + (nf == 13).to(tl.float32) * v13
        + (nf == 14).to(tl.float32) * v14
        + (nf == 15).to(tl.float32) * v15
    )

    return result.to(x.dtype)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def shifted_chebyshev_polynomial_v_func_scalar_n(x, n):
    # Scalar n version for efficiency
    xf = x.to(tl.float32)
    nf = tl.cast(n, tl.int32)

    four_x_minus_2 = 4.0 * xf - 2.0

    v0 = 1.0
    v1 = 4.0 * xf - 3.0
    v2 = four_x_minus_2 * v1 - v0
    v3 = four_x_minus_2 * v2 - v1
    v4 = four_x_minus_2 * v3 - v2
    v5 = four_x_minus_2 * v4 - v3
    v6 = four_x_minus_2 * v5 - v4
    v7 = four_x_minus_2 * v6 - v5
    v8 = four_x_minus_2 * v7 - v6
    v9 = four_x_minus_2 * v8 - v7
    v10 = four_x_minus_2 * v9 - v8
    v11 = four_x_minus_2 * v10 - v9
    v12 = four_x_minus_2 * v11 - v10
    v13 = four_x_minus_2 * v12 - v11
    v14 = four_x_minus_2 * v13 - v12
    v15 = four_x_minus_2 * v14 - v13

    # Select the correct result based on n using arithmetic masking.
    result = (
        (nf == 0).to(tl.float32) * v0
        + (nf == 1).to(tl.float32) * v1
        + (nf == 2).to(tl.float32) * v2
        + (nf == 3).to(tl.float32) * v3
        + (nf == 4).to(tl.float32) * v4
        + (nf == 5).to(tl.float32) * v5
        + (nf == 6).to(tl.float32) * v6
        + (nf == 7).to(tl.float32) * v7
        + (nf == 8).to(tl.float32) * v8
        + (nf == 9).to(tl.float32) * v9
        + (nf == 10).to(tl.float32) * v10
        + (nf == 11).to(tl.float32) * v11
        + (nf == 12).to(tl.float32) * v12
        + (nf == 13).to(tl.float32) * v13
        + (nf == 14).to(tl.float32) * v14
        + (nf == 15).to(tl.float32) * v15
    )

    return result.to(x.dtype)


def special_shifted_chebyshev_polynomial_v(x, n):
    """
    Compute the shifted Chebyshev polynomial of the third kind V_n^*(x).

    The kernel uses pre-computed recurrence values for degrees n in [0, 15].
    For n outside this range, the result is 0.0.

    Args:
        x: Input tensor (float32 only)
        n: Degree of the polynomial (int or int tensor). Supported range: [0, 15].

    Returns:
        Tensor with the same shape as x broadcasted with n
    """
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_V")
    assert x.dtype in (
        torch.float32,
    ), "Only float32 is supported for special.shifted_chebyshev_polynomial_v"

    if isinstance(n, int):
        return shifted_chebyshev_polynomial_v_func_scalar_n(x, n)
    elif isinstance(n, torch.Tensor) and n.numel() == 1:
        n_val = n.item()
        if isinstance(n_val, int):
            return shifted_chebyshev_polynomial_v_func_scalar_n(x, n_val)
    return shifted_chebyshev_polynomial_v_func(x, n)


__all__ = ["special_shifted_chebyshev_polynomial_v"]
