# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def i0_approx(x):
    """Approximation for I0(x) - modified Bessel function of first kind, order 0"""
    ax = tl.abs(x)

    # Small region: |x| <= 3.75
    t = x / 3.75
    y = t * t
    p_small = 1.0 + y * (
        3.5156229
        + y
        * (
            3.0899424
            + y * (1.2067492 + y * (0.2659732 + y * (0.0360768 + y * 0.0045813)))
        )
    )

    # Large region: |x| > 3.75
    yb = 3.75 / ax
    p_big = 0.39894228 + yb * (
        0.01328592
        + yb
        * (
            0.00225319
            + yb
            * (
                -0.00157565
                + yb
                * (
                    0.00916281
                    + yb
                    * (
                        -0.02057706
                        + yb * (0.02635537 + yb * (-0.01647633 + yb * 0.00392377))
                    )
                )
            )
        )
    )
    res_big = tl.exp(ax) * p_big / tl.sqrt(ax)

    use_small = ax <= 3.75
    return tl.where(use_small, p_small, res_big)


@triton.jit
def special_modified_bessel_k0_kernel(
    x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    x_f32 = x.to(tl.float32)

    # K0 is only defined for x > 0
    # For x < 0, return NaN (matching PyTorch behavior)
    # For x = 0, return inf (singularity)
    is_negative = x_f32 < 0.0
    is_zero = x_f32 == 0.0

    # Compute I0(x) for use in the small region formula
    i0_x = i0_approx(x_f32)

    # Small region: 0 < x <= 2.0
    # Use the relation: K0(x) = -ln(x/2) * I0(x) + poly(x^2/4)
    # where poly was fitted to match scipy's k0 exactly
    y = x_f32 * x_f32 / 4.0  # y = (x/2)^2

    # Fitted polynomial coefficients (from scipy's k0)
    # diff(y) = 0.000129 * y^5 + 0.00260 * y^4 + 0.0349 * y^3 + 0.231 * y^2 + 0.423 * y - 0.577
    p = -0.57721566
    p = p + 0.42278441 * y
    p = p + 0.23069500 * y * y
    p = p + 0.03488730 * y * y * y
    p = p + 0.00260380 * y * y * y * y
    p = p + 0.00012900 * y * y * y * y * y

    small_result = -tl.log(x_f32 * 0.5 + 1e-40) * i0_x + p

    # Large region: x > 2.0
    # Use asymptotic expansion: K0(x) ~ sqrt(pi/(2x)) * exp(-x) * Q(2/x)
    t = 2.0 / x_f32  # t = 2/x

    # Polynomial Q(t) for K0 large region
    q = 1.25331414
    q = q - 0.07832324 * t
    q = q + 0.0218956 * t * t
    q = q - 0.01072842 * t * t * t
    q = q + 0.00162318 * t * t * t * t
    q = q - 0.00013259 * t * t * t * t * t

    large_result = q * tl.exp(-x_f32) / tl.sqrt(x_f32 + 1e-40)

    # Select based on x value
    use_small = x_f32 <= 2.0
    result = tl.where(use_small, small_result, large_result)

    # Handle edge cases: x < 0 -> NaN, x = 0 -> inf, x > 0 -> result
    result = tl.where(is_negative, float("nan"), result)
    result = tl.where(is_zero, float("inf"), result)

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_special_modified_bessel_k0(x: torch.Tensor, out: torch.Tensor):
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert (
        x.numel() == out.numel()
    ), "Input and output must have the same number of elements"
    assert x.dtype == out.dtype, "Input and output must have the same dtype"

    n_elements = x.numel()
    if n_elements == 0:
        return

    # BLOCK_SIZE 1024 provides good occupancy for element-wise kernels on H20
    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        special_modified_bessel_k0_kernel[grid](
            x, out, n_elements, BLOCK_SIZE=BLOCK_SIZE
        )


def special_modified_bessel_k0(self: torch.Tensor):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_K0")
    x = self
    x_c = x.contiguous()
    out = torch.empty_like(x_c)
    _launch_special_modified_bessel_k0(x_c, out)
    if x.layout == torch.strided and x.is_contiguous():
        return out
    else:
        return out.view_as(x)


def special_modified_bessel_k0_out(self: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_K0_OUT")
    x = self
    if out.dtype != x.dtype:
        raise TypeError("out dtype must match input dtype")
    if out.device != x.device:
        raise TypeError("out device must match input device")

    x_c = x.contiguous()
    out_c = out.contiguous()
    _launch_special_modified_bessel_k0(x_c, out_c)
    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out
