# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


# Chebyshev polynomial of the second kind U_n(x)
# Using explicit polynomial formulas for n = 0..5:
# U_0(x) = 1
# U_1(x) = 2x
# U_2(x) = 4x^2 - 1
# U_3(x) = 8x^3 - 4x
# U_4(x) = 16x^4 - 12x^2 + 1
# U_5(x) = 32x^5 - 32x^3 + 6x
# Limitation: only n ∈ [0, 5] is supported. The wrapper raises ValueError for
# values outside this range. For higher orders a general recurrence is needed.
@pointwise_dynamic(is_tensor=[True, True], promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def special_chebyshev_polynomial_u_kernel(x, n):
    """Compute Chebyshev polynomial U_n(x) where both x and n are tensors.

    Note: The argument order is (x, n) to match torch.special.chebyshev_polynomial_u

    Limitation: only n ∈ [0, 5] is supported. n values outside this range are
    rejected by a guard in the wrapper before the kernel is invoked.
    """
    x_f32 = x.to(tl.float32)
    n_int = n.to(tl.int32)

    one = 1.0
    x2 = x_f32 * x_f32
    x3 = x2 * x_f32
    x4 = x3 * x_f32
    x5 = x4 * x_f32

    # Compute polynomials for n = 0, 1, 2, 3, 4, 5
    u0 = one  # U_0(x) = 1
    u1 = 2.0 * x_f32  # U_1(x) = 2x
    u2 = 4.0 * x2 - one  # U_2(x) = 4x^2 - 1
    u3 = 8.0 * x3 - 4.0 * x_f32  # U_3(x) = 8x^3 - 4x
    # U_4(x) = 16x^4 - 12x^2 + 1
    u4 = 16.0 * x4 - 12.0 * x2 + one
    # U_5(x) = 32x^5 - 32x^3 + 6x
    u5 = 32.0 * x5 - 32.0 * x3 + 6.0 * x_f32

    # Select based on n
    result = tl.where(
        n_int == 0,
        u0,
        tl.where(
            n_int == 1,
            u1,
            tl.where(
                n_int == 2, u2, tl.where(n_int == 3, u3, tl.where(n_int == 4, u4, u5))
            ),
        ),
    )

    return result.to(x.dtype)


def special_chebyshev_polynomial_u(x, n):
    """Compute the Chebyshev polynomial of the second kind U_n(x).

    Args:
        x: The input tensor.
        n: The order of the polynomial. Can be a scalar, int, float, or tensor.

    Returns:
        The Chebyshev polynomial U_n(x) evaluated at x.
    """
    logger.debug("GEMS SPECIAL_CHEBYSHEV_POLYNOMIAL_U")
    assert x.dtype == torch.float32, f"unsupported dtype {x.dtype}"

    if isinstance(n, torch.Tensor):
        # Run the range guard on a CPU copy to avoid dispatching back into the
        # gems reduction kernels while use_gems() is active.
        n_ref = n.detach().to("cpu", dtype=torch.int32)
        n_min = int(n_ref.amin().item())
        n_max = int(n_ref.amax().item())
        n = n.to(device=x.device, dtype=torch.int32)
    else:
        n_min = n_max = int(n)
        n = torch.tensor(n_min, dtype=torch.int32, device=x.device)

    # Guard: only n ∈ [0, 5] is supported by the explicit polynomial formulas.
    if n_max > 5 or n_min < 0:
        raise ValueError(
            f"Chebyshev polynomial order n must be in [0, 5], "
            f"got values in [{n_min}, {n_max}]"
        )

    return special_chebyshev_polynomial_u_kernel(x, n)
