# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def shifted_chebyshev_polynomial_w_func(x, n):
    # Shifted Chebyshev polynomial of the second kind: W_n(x)
    # Formula:
    # W_0(x) = 1
    # W_1(x) = 4x - 1 = 2(2x - 1) + 1
    # W_n(x) = (4x - 2) * W_{n-1}(x) - W_{n-2}(x)
    #
    # Using y = 2x - 1:
    # W_0 = 1
    # W_1 = 2y + 1
    # W_n = 2y * W_{n-1} - W_{n-2}

    x_val = x.to(tl.float32)
    n_val = n.to(tl.int32)

    # Compute y = 2x - 1
    y = 2.0 * x_val - 1.0

    # Base cases
    result = tl.where(
        n_val == 0,
        1.0,
        tl.where(
            n_val == 1,
            2.0 * y + 1.0,
            # For n >= 2, use recurrence
            _compute_w(y, n_val),
        ),
    )
    return result.to(x.dtype)


@triton.jit
def _compute_w(y, n):
    # Generic computation for n >= 2 using recurrence
    # W_n = 2y * W_{n-1} - W_{n-2}
    t0 = 1.0  # W_0 = 1
    t1 = 2.0 * y + 1.0  # W_1 = 2y + 1

    # Unrolled loop for small n values
    t2 = 2.0 * y * t1 - t0  # n=2
    t3 = 2.0 * y * t2 - t1  # n=3
    t4 = 2.0 * y * t3 - t2  # n=4
    t5 = 2.0 * y * t4 - t3  # n=5
    t6 = 2.0 * y * t5 - t4  # n=6
    t7 = 2.0 * y * t6 - t5  # n=7
    t8 = 2.0 * y * t7 - t6  # n=8
    t9 = 2.0 * y * t8 - t7  # n=9
    t10 = 2.0 * y * t9 - t8  # n=10

    # Use sequential tl.where for clarity instead of deep nesting
    result = t10
    result = tl.where(n == 2, t2, result)
    result = tl.where(n == 3, t3, result)
    result = tl.where(n == 4, t4, result)
    result = tl.where(n == 5, t5, result)
    result = tl.where(n == 6, t6, result)
    result = tl.where(n == 7, t7, result)
    result = tl.where(n == 8, t8, result)
    result = tl.where(n == 9, t9, result)
    result = tl.where(n == 10, t10, result)
    return result


def special_shifted_chebyshev_polynomial_w(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_W")
    assert x.dtype in (
        torch.float32,
        torch.float64,
    ), "shifted_chebyshev_polynomial_w only supports float32 and float64"
    if torch.any(n > 10):
        raise ValueError(
            "n must be <= 10, got values up to {}. "
            "The unrolled kernel only supports n <= 10.".format(int(n.max().item()))
        )
    return shifted_chebyshev_polynomial_w_func(x, n)
