# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def special_sinc_func(x):
    # Compute normalized special_sinc: sin(pi * x) / (pi * x)
    # When x == 0, special_sinc(x) = 1
    x_f32 = x.to(tl.float32)
    pi = math.pi
    pi_x = pi * x_f32
    # Handle x == 0 case to avoid division by zero
    # special_sinc(0) = 1
    return tl.where(x_f32 == 0.0, 1.0, tl.sin(pi_x) / pi_x)


def special_sinc(A):
    logger.debug("GEMS SPECIAL_SINC")
    return special_sinc_func(A)
