# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def special_modified_bessel_k1_func(x):
    # Modified Bessel function of the second kind, order 1: K_1(x)
    # K_1(x) is defined for x > 0
    #
    # Implementation using series + asymptotic with linear blend
    # Series: accurate for x < 0.5
    # Asymptotic: accurate for x > 1.5
    # Linear blend in between

    # Constants
    gamma = 0.577215664901532860606512090082402431042159335
    sqrt_pi_over_2 = 1.2533141373155002512078826424055  # sqrt(pi/2)

    x = x.to(tl.float32)

    # Handle x <= 0: return NaN for non-positive values
    is_non_positive = x <= 0.0
    x_safe = tl.where(x <= 0.0, 0.1, x)

    # Compute log(x/2) and related terms
    log_half = tl.log(x_safe / 2.0)
    ln_term = log_half + gamma

    # Series expansion for very small x (x < 0.5)
    x2 = x_safe * x_safe
    x4 = x2 * x2
    x6 = x4 * x2
    x8 = x4 * x4
    x10 = x8 * x2

    term1 = 1.0 / x_safe
    term2 = x_safe / 2.0 * (ln_term - 0.5)
    term3 = x2 * x_safe / 16.0 * (ln_term - 5.0 / 6.0)
    term4 = x4 * x_safe / 128.0 * (ln_term - 23.0 / 24.0)
    term5 = x6 * x_safe / 2304.0 * (ln_term - 235.0 / 276.0)
    term6 = x8 * x_safe / 41472.0 * (ln_term - 1469.0 / 1560.0)
    term7 = x10 * x_safe / 74304.0 * (ln_term - 7519.0 / 7080.0)

    series_result = term1 + term2 + term3 + term4 + term5 + term6 + term7

    # Asymptotic expansion for larger x (x > 1.5)
    x_inv = 1.0 / x_safe
    x_inv2 = x_inv * x_inv
    x_inv3 = x_inv2 * x_inv

    asymp_correction = (
        1.0 + 3.0 / 8.0 * x_inv - 15.0 / 128.0 * x_inv2 + 105.0 / 1024.0 * x_inv3
    )
    asymp_result = sqrt_pi_over_2 / tl.sqrt(x_safe) * tl.exp(-x_safe) * asymp_correction

    # Linear blend from series to asymptotic
    # At x <= 0.5: blend = 1.0 (series only)
    # At x >= 1.5: blend = 0.0 (asymptotic only)
    # Between 0.5 and 1.5: linear interpolation
    blend = tl.where(
        x_safe <= 0.5, 1.0, tl.where(x_safe >= 1.5, 0.0, 1.0 - (x_safe - 0.5) / 1.0)
    )

    result = series_result * blend + asymp_result * (1.0 - blend)

    # Handle non-positive values: compute fp32 NaN without fp64 constant
    # to avoid IXRTC ERROR_UNSUPPORTED_CAST
    zero = x - x
    result = tl.where(is_non_positive, zero / zero, result)

    return result.to(x.dtype)


def special_modified_bessel_k1(A):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_K1")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), "special_modified_bessel_k1 only supports float32 and float64"
    return special_modified_bessel_k1_func(A)


def special_modified_bessel_k1_out(A, out):
    logger.debug("GEMS SPECIAL_MODIFIED_BESSEL_K1_OUT")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), "special_modified_bessel_k1_out only supports float32 and float64"
    if out.dtype != A.dtype:
        raise TypeError("out dtype must match input dtype")
    if out.device != A.device:
        raise TypeError("out device must match input device")
    result = special_modified_bessel_k1_func(A)
    out.copy_(result)
    return out
