# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, "DEFAULT")])
@triton.jit
def _erfc_kernel(x):
    output = tl_extra_shim.erfc(x.to(tl.float32))
    return output


def erfc(x):
    logger.debug("GEMS ERFC")
    return _erfc_kernel(x)


def special_erfc(x):
    logger.debug("GEMS SPECIAL_ERFC")
    return _erfc_kernel(x)


def erfc_(x):
    logger.debug("GEMS ERFC_")
    return _erfc_kernel(x, out0=x)
