# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _squeeze_copy_kernel(src_ptr, dst_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    vals = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, vals, mask=mask)


def squeeze_copy(x: torch.Tensor):
    """Wrapper for aten::squeeze_copy.

    Returns a copy of the input tensor with all dimensions of size 1 removed.
    """
    logger.debug("GEMS SQUEEZE_COPY")
    # Compute squeezed shape: all dims != 1, or empty if all dims were 1
    squeezed_shape = [s for s in x.shape if s != 1]

    # Create output tensor with squeezed shape (empty list means 0-d tensor)
    out = torch.empty(squeezed_shape, dtype=x.dtype, device=x.device, layout=x.layout)
    n_elements = out.numel()
    if n_elements == 0:
        return out

    # Ensure input is contiguous for efficient linear access
    src = x.contiguous() if not x.is_contiguous() else x
    if not out.is_contiguous():
        out = out.contiguous()

    if src.dtype != out.dtype:
        raise RuntimeError("squeeze_copy: dtype mismatch between input and output.")
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        _squeeze_copy_kernel[grid](src, out, n_elements, BLOCK_SIZE=1024)
    return out
