# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton

logger = logging.getLogger(__name__)


@triton.jit
def sym_stride_kernel(x):
    # Return 1 for all elements - stride info is metadata, not computed
    # This kernel is a placeholder since sym_stride returns tensor metadata
    return 1


def sym_stride(A):
    """Returns the stride of the input tensor.

    This operator returns the stride of the input tensor as a list of integers.
    It is used for torch.compile symbolic tracing.
    """
    logger.debug("GEMS SYM_STRIDE")
    # sym_stride returns tensor metadata (stride), not a computed tensor
    # For FlagGems integration, we return the actual stride
    return A.stride()
