# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def take_kernel(in_ptr, idx_ptr, out_ptr, n_index, in_numel, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offs = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offs < n_index

    idx = tl.load(idx_ptr + offs, mask=mask, other=0)
    # torch.take supports negative indices: wrap them into [0, in_numel).
    idx = tl.where(idx < 0, idx + in_numel, idx)

    # Bounds check aligned with PyTorch's CUDA behavior: an out-of-range index
    # trips a device-side assert (asynchronous). Enable via TRITON_DEBUG=1.
    valid = (idx >= 0) & (idx < in_numel)
    tl.device_assert(valid | (~mask), "take(): index out of range")

    # Clamp the read with `valid` so an out-of-range index never dereferences
    # illegal memory even when the assert is compiled out.
    vals = tl.load(in_ptr + idx, mask=mask & valid, other=0)
    tl.store(out_ptr + offs, vals, mask=mask)


def _launch_take(input, index, out_flat):
    input_flat = input.contiguous().view(-1)
    in_numel = input_flat.numel()
    n_index = index.numel()
    if n_index == 0:
        return
    # Feed the kernel native int64 indices; address math stays 64-bit and we
    # avoid an extra full-tensor dtype-conversion pass over the index.
    index_flat = index.contiguous().view(-1)
    grid = lambda meta: (triton.cdiv(n_index, meta["BLOCK_SIZE"]),)  # noqa: E731
    with torch_device_fn.device(input.device):
        take_kernel[grid](
            input_flat, index_flat, out_flat, n_index, in_numel, BLOCK_SIZE=1024
        )


def take(input, index):
    logger.debug("GEMS TAKE")
    if input.device != index.device:
        raise RuntimeError("input and index must be on the same device")
    out_flat = torch.empty(index.numel(), device=input.device, dtype=input.dtype)
    _launch_take(input, index, out_flat)
    return out_flat.view(index.shape)


def take_out(input, index, *, out):
    logger.debug("GEMS TAKE_OUT")
    if not (input.device == index.device == out.device):
        raise RuntimeError("input, index and out must be on the same device")
    if out.dtype != input.dtype:
        raise RuntimeError(f"out must have dtype {input.dtype}, but got {out.dtype}")
    if tuple(out.shape) != tuple(index.shape):
        out.resize_(index.shape)
    if out.is_contiguous():
        out_flat = out.view(-1)
        _launch_take(input, index, out_flat)
    else:
        tmp_flat = torch.empty(index.numel(), device=input.device, dtype=input.dtype)
        _launch_take(input, index, tmp_flat)
        out.copy_(tmp_flat.view(index.shape))
    return out
