# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, False, False], promotion_methods=[(0, "DEFAULT")])
@triton.jit
def threshold_func(x, threshold, value):
    # Perform computation in float32 for precision
    x_fp32 = x.to(tl.float32)
    threshold_fp32 = threshold.to(tl.float32)
    value_fp32 = value.to(tl.float32)
    # If x <= threshold, return value, otherwise return x
    return tl.where(x_fp32 <= threshold_fp32, value_fp32, x_fp32).to(x.dtype)


def threshold_(A, threshold, value):
    logger.debug("GEMS THRESHOLD_")
    return threshold_func(A, threshold, value, out0=A)
