# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def unfold(self: torch.Tensor, dimension: int, size: int, step: int) -> torch.Tensor:
    r"""Return a view with an added dimension of sliding windows along ``dimension``.

    Each window is a slice of size ``size``, taken every ``step`` elements.
    The returned tensor has an extra last dimension of size ``size``.

    Args:
        self (torch.Tensor): Input tensor.
        dimension (int): Dimension along which to unfold.
        size (int): Size of each sliding window.
        step (int): Step between consecutive windows.

    Returns:
        torch.Tensor: A view of the input with an additional dimension.
    """
    logger.debug("GEMS UNFOLD")

    ndim = self.ndim
    if ndim == 0:
        # PyTorch allows unfold on 0-d tensors with dimension=0, size<=1, step>=1
        dimension = 0
    else:
        # Handle negative dimension
        if dimension < 0:
            dimension += ndim

    dim_size = 1 if ndim == 0 else self.size(dimension)

    if size > dim_size:
        raise RuntimeError(
            f"Maximum size for tensor at dimension {dimension} is {dim_size} "
            f"but size is {size}"
        )
    if step <= 0:
        raise RuntimeError(f"Step must be > 0, got {step}")

    # Number of windows
    n_windows = (dim_size - size) // step + 1

    # Build new shape: replace dim with n_windows, append size
    new_shape = list(self.shape)
    if ndim == 0:
        new_shape = [n_windows, size]
    else:
        new_shape[dimension] = n_windows
        new_shape.append(size)

    # Build new strides: stride at dim becomes stride*step, append original stride at dim
    old_strides = list(self.stride()) if ndim > 0 else [1]
    dim_stride = old_strides[dimension] if ndim > 0 else 1

    new_strides = list(old_strides) if ndim > 0 else []
    if ndim == 0:
        new_strides = [step * dim_stride, dim_stride]
    else:
        new_strides[dimension] = step * dim_stride
        new_strides.append(dim_stride)

    return self.as_strided(new_shape, new_strides, self.storage_offset())
