# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch

logger = logging.getLogger(__name__)


def unsafe_chunk(A: torch.Tensor, chunks: int, dim: int = 0) -> List[torch.Tensor]:
    r"""Split a tensor into :attr:`chunks` pieces along the given dimension.

    The last chunk will be smaller if the tensor size along the given
    dimension is not divisible by :attr:`chunks`.

    Args:
        A (torch.Tensor): Input tensor.
        chunks (int): Number of chunks to produce.
        dim (int): Dimension along which to split the tensor.

    Returns:
        List[torch.Tensor]: List of tensors.
    """
    logger.debug("GEMS UNSAFE_CHUNK")

    # Handle negative dim
    if dim < 0:
        dim = dim + A.ndim

    # Calculate the size of each chunk
    dim_size = A.size(dim)
    chunk_size = (dim_size + chunks - 1) // chunks  # ceiling division

    # Create list to hold chunks
    result = []

    for i in range(chunks):
        # Calculate start and end indices for this chunk
        start = i * chunk_size
        end = min(start + chunk_size, dim_size)

        # Handle the case where this chunk would be empty
        if start >= dim_size:
            break

        # Create slice for this chunk
        slices = [slice(None)] * A.ndim
        slices[dim] = slice(start, end)

        # Extract chunk using indexing
        chunk = A[tuple(slices)]
        result.append(chunk)

    return result
