# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def unsqueeze(A: torch.Tensor, dim: int) -> torch.Tensor:
    """Insert a dimension of size 1 at the specified position.

    This is a zero-copy view operation that adjusts shape and strides.
    No data is copied.

    Args:
        A: Input tensor
        dim: Index at which to insert the singleton dimension

    Returns:
        View of the input tensor with a dimension of size 1 inserted
    """
    logger.debug("GEMS UNSQUEEZE")

    ndim = A.dim()

    # Validate and normalize dim
    if dim < 0:
        dim = ndim + dim + 1

    if dim < 0 or dim > ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of [0, {ndim}], "
            f"but got {dim})"
        )

    new_shape = list(A.shape)
    new_shape.insert(dim, 1)

    # reshape delegates stride computation to PyTorch
    return A.reshape(new_shape)


def unsqueeze_(A: torch.Tensor, dim: int) -> torch.Tensor:
    """In-place version of unsqueeze (zero-copy view operation).

    Mutates ``A`` itself: the new singleton dimension is inserted into
    ``A``'s shape/strides in place, so the change is visible through ``A``
    (and any alias of it), matching the semantics of
    ``torch.Tensor.unsqueeze_``.

    The unsqueezed view is built with :func:`unsqueeze` and rebound onto
    ``A`` via ``Tensor.set_`` so the metadata mutation is applied to ``A``
    in place, then ``A`` is returned.
    """
    logger.debug("GEMS UNSQUEEZE_")
    out = unsqueeze(A, dim)
    A.set_(out)
    return A
